# \chapterprecis{\Glspl{gw} were perhaps the last of the
#   predictions of Einstein's General Theory of Relativity to be
#   observed; their detection was the catalyst for the beginning of a
#   new era of astrophysics}

# \epigraph{I guess we need to do the detection checklist...}{\textbf{Sergey Klimencko}, \emph{Internal LSC communication}, 14 September 2015}

\lettrine[lines=3]{T}{he 14 September 2016} will likely be remembered as one of the most significant in the history of astronomy and of astrophysics. 
Early in the morning of this autumn day, shortly after 9am UT, a gravitational wave passed through the Earth, 
and on its way produced a sufficiently large movement in the mirrors and test masses of the detectors of the gls:ligo, as to be detected.

Over five months of data analysis, detector characterisation, and detection verification were conducted by a global team of scientists, in the gls:ligo and gls:virgo Scientific Collaboration (LVC). 
This process resulted in a slew of journal papers being written, vast quantities of data produced, and an enormous public outreach effort to be launched. 
Eventually, the collaboration found itself in a position to make the announcement of the first direct detection of gravitational waves, gls:gw150914, on 11 February 2016.

Further discoveries were made during the first observing run of the gls:advanced-ligo facilities, gls:lvt151012, observed in October, and gls:gw151226, observed in December, added to the menagerie of directly detected black hole binaries (although the significance of the former was insufficient to garner its own press release and announcement publication). 
The majority of 2016 was dedicated to introducing upgrades to the two gls:ligo interferometers, and to comissioning a third second-generation interferometric observatory, gls:virgo, located in Italy.
The second observation run of gls:advanced-ligo, which was scheduled to be longer and more sensitive than its first lead to the observation of three further binary black hole coalescences, gls:gw170104, gls:gw170608, and gls:gw170814, the latter observed by a network of three detectors, gls:virgo having joined the observing run a short time before.

gls:gw150914 is not the first evidence for gravitational waves, with the Hulse-Taylor pulsar cite:1975ApJ...195L..51H,2005ASPC..328...25W having provided compelling indirect evidence which lead to its
discoverers receiving the 1993 Nobel Prize.

This chapter serves as a brief overview of the mathematical and physical motivation for the search for gravitational waves (), the current network of gravitational wave detectors (), and a synopsis of the first gravitational wave detections. 
In addition a primer on the conventions used in the description of gravitational wave signals is included in ().

* Gravitational Waves and General Relativity
#+NAME: sec:general-relativity

Gravitational waves are one of the predictions of Einstein's 1915 Theory of General Relativity cite:1915SPAW.......844E, with the first theoretical prediction of their existence being proposed by Einstein in 1916 cite:1937FrInJ.223...43E,1918SPAW.......154E, less than a year after the publication of the general theory, however research work in this area remained largely stagnant until the 1960s, when interest in the field picked-up *hmm, may want to cut this line, or else add more detail*.

The behaviour of gravitational fields in the presence of mass is modelled, in General Relativity, by the gls:einstein-field-equations,

\begin{equation}
\label{eq:einsteinfieldequations}
 R_{\mu \nu} - \frac{1}{2} R g_{\mu \nu} = \frac{8 \pi G}{c^{4}} T_{\mu \nu},
\end{equation}

for $R_{\mu \nu}$ is the gls:ricci-tensor, which represents the amount by which a sphere is distorted at a point in spacetime[fn:ricci-tensor], $R$ the gls:ricci-scalar [fn:ricci-scalar], the trace of the Ricci tensor, $g_{\mu \nu}$ is the metric tensor, which describes the local geometry of spacetime at any given point, and $T_{\mu \nu}$ the stress-energy tensor, which encapsulates the density and time-variation of energy and momentum at any given point in spacetime.

Contracting equation ref:eq:einsteinfieldequations with a timelike unit vector allows a reduction to a situation with a defined direction of time, with this contraction leading to the revalation that spacetime curvature, $R$, is produced by the mass-energy density, since the constraction of a timelike vector with the stress-energy tensor returns simply the mass-energy density, $\rho$, in a dust, we find
\[ R = - 4 \pi G \rho \]
leading to the second-half of the famous aphorism,
#+BEGIN_quote
Spacetime tells matter how to move; matter tells spacetime how to curve. ---John Archibald Wheeler cite:geonsblackholes
#+END_quote

Despite their apparent simplicity, the Einstein Field Equations, are highly non-linear in $\ten{g}$, and only a few exact solutions are known. While some of these solutions, which include the Schwarzchild solution (for the behaviour of spacetime close to a non-spinning singularity), and the Kerr solution (for the spacetime close to a rotating singularity) are exact and tractable, the majority of scenarios lead to non-analytical solutions which must be explored numerically. 
While the Einstein equations provide this valuable insight into the behaviour of a static system, it is more often of interest to consider dynamic systems, and the time-evolution of the system.
One approach to dealing with the non-linearity of the field equations is to "linearise" the theory, by assuming first a known solution of the field equations, $\eta_{\mu\nu}$ and then producing a small perturbation on that solution, $h_{\mu\nu}$. This approach is introduced in, for example, cite:mtw, and provided that the size of the perturbation is sufficiently small, provides a means of investigating the model in "weak-field" scenarios. Such an approach is suitable for the study of the evolution of the weak-field. 
The metric in such a scenario takes the form 
\begin{equation}
\label{eq:linearised-metric}
g_{\mu\nu} = \eta_{\mu\nu} + h_{\mu\nu}.
\end{equation}
Allowing $\bar{h} \gets h$ representing a rescaling [fn:metric-rescale] of the perturbation, $\bar{h} = h_{\mu \nu} - 1/2\, \eta_{\mu \nu} h$. We can then make a choice of gauge, the Lorentz (or Hilbert) gauge, by specifying $\bar{h}\indices{^{\mu\nu}_{,\nu}} = 0$.

The derivative of the metric then describes the propagation of the perturbation,
\begin{equation}
\label{eq:wave-equation-gw}
\dalembert \barh \equiv \bar{h}\indices{_{\mu\nu,\alpha}^{\alpha}} = 0,
\end{equation}
which has plane-wave solutions of the form
\begin{equation}
   \label{eq:planewavegw}
   \barh = \real \left[ A_{\mu\nu} \exp\left(i k_{\alpha}x^{\alpha}\right) \right]
\end{equation}
for a null wavevector, $\vec{k}$, orthonormal to an amplitude $\ten{A}$. Provided a transverse, traceless [fn:tt-gauge] gauge is chosen, the amplitude tensor takes the form 
\begin{equation}
\label{eq:ttamplitudetensor}
\ten{A} = 
   \begin{bmatrix}
   0 & 0 & 0 & 0\\
   0 & A_{xx} & A_{xy} & 0\\
   0 & A_{xy} & -A_{xx} & 0\\
   0 & 0 & 0 & 0
   \end{bmatrix}.
\end{equation}

It is clear from the form of the plane-wave solution, in equation ref:eq:planewavegw that a wave propagates in spacetime in a manner quite different from a wave on, for example, the surface of a loch: rather than a vector perturbation, a abbr:gw propagates as a tensoric perturbation. The conventional method used to visualise this effect involves considering the effect of a gravitational wave traveling perpendicular to a ring of test particles. 
For such a wave, propagating along the $z$-axis, in the transverse-traceless gauge, the only non-vanishing components of the strain are
\[ h_{xx} = - h_{yy} = \real[ A_{xx} \exp(- \ii \omega (t-z) ], \]
and 
\[ h_{xy} = h_{yx} = \real[ A_{xy} \exp(- \ii \omega(t-z) ]. \]
The propagation can then be desccribed as the superposition of two linearly-polarised components; the unit polarisation tensors can be derived from the coordinate basis as 
\begin{align}
\label{eq:gwpolarisationbasis}
 \ten{e}_{+} &= \ten{e}_{x} \otimes \ten{e}_{x} - \ten{e}_{y} \otimes \ten{e}_y\\
 \ten{e}_{\times} &= \ten{e}_{x} \otimes \ten{e}_{y} + \ten{e}_{y} \otimes \ten{e}_{x}
\end{align}
As the wave passes orthogonally through the circular ring of test particles they will be distorted into an ellipse. For the $+$-polarisation the circle is stretched into an ellipse with semi-major axis first extending along the $x$-axis, relaxing back to a circle, and then again with a semi-major axis extending along the $y$-axis.\\
\begin{tikzpicture}[xscale=0.45, yscale=0.45]
   \def\w{1.5}
    \foreach \i in {0,...,18}{
       \def\a{-90+30*\i}
       \draw [domain=0:360, thick] plot ( {\w*\i +0.5*(cos(\x)*(1+0.4*cos(\a))) }, {0.5*(sin(\x)*(1-0.4*cos(\a)))});
    };
\end{tikzpicture}\\
Equivalently, the $\times$-polarisation produces a deformation rotated $45^{\circ}$ relative to the $+$-polarisation.\\
 \begin{tikzpicture}[xscale=0.27, yscale=0.27]
    \def\w{2.5}
     \foreach \i in {0,...,18}{
        \def\a{90+30*\i}
        \draw [domain=0:360, thick] plot ({\w*\i + cos(\x) + 0.25*sin(\x)*0.5*cos(\a) }, {sin(\x) +0.25*cos(\x)*0.5*cos(\a) });
     };
 \end{tikzpicture}

Further, the behaviour of "strong-field gravity", which is essential to understanding the production of gravitational waves must be probed using this method. 
As a result both the analysis of gravitational waves, and their astrophysical interpretation, relies on the ability to solve the field equations numerically.

\begin{equation}
\label{eq:intro:gr:mass-quadrupole}
Q_{jk} = \int \rho x_k x_k \frac{\dd^3}{\dd x^3}
\end{equation}
and the gravitational wave is described by the three-tensor
\begin{equation}
\label{eq:intro:gr:quadrupole2strain}
  h_{jk} = \frac{2}{r} \frac{\dd^2 Q_{jk}}{}
\end{equation}

[fn:ricci-tensor] More precisely, the gls:ricci-tensor, which is the trace of the Riemann tensor, describes how the distance between the points within a volume varies as the entire volume is parallel-transported over a curved manifold, compared to the same movement over a flat manifold.

[fn:ricci-scalar] The gls:ricci-scalar is the trace of the gls:ricci-tensor, and represents the deviation in the area of an $(N-1)$-dimensional sphere in a curved $N$-dimensional space compared to a flat $N$-dimensional space.

[fn:metric-rescale] This rescaling of the metric has no physical consequence, but substanitally simplifies the number of quantities composing the Einstein tensor.

[fn:tt-gauge] Explain the TT gauge here.

* A network of detectors
#+NAME: sec:detector-network

#+NAME:fig:gwspectrum
#+ATTR_LATEX: :width \textwidth
#+CAPTION: The gravitational wave spectrum, with a number of current and future detectors' sensitivity curves overlaid.
[[./figures/gw-spectrum.pdf]]

/This section should give a very brief overview of the advanced LIGO and advanced Virgo network; this is discussed in much more detail in the detectors chapter, but a few paragraphs worth of description of the network would be valuable in the context of the early observations./ 

Generally, in order to make a confident detection of a gravitational wave the event must be observed in at least two detectors; this is principally due to the need to exclude noise sources as the source of the signal. A true gravitational wave event should be coincident (within the wave travel-time between any pair of detectors) in two or more detectors, whereas locally produced noise will appear only in the observations of a single detector, or with a time-lag which is not physically consistent with a gravitational wave. The largely omnidirectional sensitivity of interferometric detectors further motivates the need for multiple detectors which can be used to triangulate the source of the signal in the sky.

At the time of writing the world-wide network of gravitational wave detectors was made-up of four interferometric detectors: the gls:geo600 detector in Germany, the advanced gls:virgo detector in Italy, and two advanced gls:ligo detectors, located in the USA states of Washington and Louisiana. The normal operation of the network omits the less sensitive gls:geo600 detector, and is capable of operating as a network containing all three detectors, or two detectors during periods of time where one detector is not observing.

Additional detectors are currently either being planned or are under construction which will see an increase both in the number of detectors and their geographical spread. Such an increased network should provide both an increased duty cycle (leading to a decrease in the total time when no observations are being made), and improved sky-localisation capability (improving the prospects of successful electromagnetic follow-up of gravitational wave events).


* GW150914: The first detection
#+NAME: sec:gw150914-intro

This section should be a mixture of the history of the detection and the science of the event itself; this and GW170817 will be the only events to have this much detail.

* GW170817: The first multi-messenger detection
#+NAME: sec:gw170817-intro

Again, the history of this event, and its science, is sufficiently distinctive to earn itself around a page of discussion here. 

* Catalogue of observations
#+NAME: sec:gw-catalogue

The remaining observations should be discussed here with reference to the catalogue paper, as a suitable overview is desirable, but excessive detail is not.

#+LATEX_ATTR: :booktabs
#+NAME: tab:eventlist
#+CAPTION: A summary table of the eleven significant gravitational events observed during the first two observing runs of the LIGO-Virgo network. 
| Catalogue number | Type | Mass 1 | Mass 2 |
|------------------+------+--------+--------|
| GW150914         | BBH  |        |        |
| GW151012         | BBH  |        |        |
| GW151226         | BBH  |        |        |
| GW170104         | BBH  |        |        |
| GW170608         | BBH  |        |        |
| GW170729         | BBH  |        |        |
| GW170809         | BBH  |        |        |
| GW170814         | BBH  |        |        |
| GW170817         | BNS  |        |        |
| GW170818         | BBH  |        |        |
| GW170823         | BBH  |        |        |

* Observing scenarios
/A discussion of the various observing scenarios should be presented here, with some brief discussion of the first two observing runs, and the prospects for O3 and beyond, including the inclusion of the KAGRA detector. Potential to mention 3G detectors towards the end, but this may be held back for detectors chapter./

The gravitational wave community are in the fortunate position of the field having advanced both to the so-called /advanced/-era, in which interferometric detectors sensitivity has increased sufficiently to make observations plausible, but also the /observational/-era; the perfect coincidence of these two epochs is surely one of the less believable twists in the plot of scientific history. As a result most of this work will consider the state of gravitational wave detection in the observational era, starting in the early observational period: the first two observing runs of the advanced gls:ligo detectors, and the first observing run of the advanced gls:virgo detector; looking ahead to future observing runs involving a larger network of gravitational wave detectors, including gls:kagra and an additional advanced gls:ligo detector located in India.

The first two observing runs have provided some information about the rate of the events which produce detectable gravitational waves, allowing better constraints to be placed on anticipated observed event rates as the detectors continue to develop over the next decade. The current estimates of likely abbr:bns rates are given in table ref:tab:ratescenarios.

  #+NAME: tab:rangescenarios
  #+ATTR_LATEX: :booktabs :placement [b]
  #+CAPTION: The anticipated sensitivities of the various second-generation detectors throughout their development, measured in terms of the abbr:BNS gls:horizon-distance, which represents the average maximal distance at which the signal from a binary neutron star coalesence could be observed. This table was adapted from the information in cite:2018LRR....21....3A.
  | Epoch  | LIGO  (Mpc) | Virgo (Mpc) | KAGRA (Mpc) |
  |--------+-------------+-------------+-------------|
  | Early  | 40 - 80     | 20 - 65     | 8 - 25      |
  | Mid    | 80 - 120    | 68 - 85     | 25 - 40     |
  | Late   | 120 - 170   | 65 - 155    | 40 - 140    |
  | Design | 190         | 125         | 140         |


  #+NAME: tab:ratescenarios
  #+ATTR_LATEX: :booktabs :placement [b]
  #+CAPTION: The anticipated observed abbr:BNS rate throughout the development stages of the second-generation detector network. The observation rate is limited by the abbr:BNS gls:horizon-distance and the combined network gls:duty-cycle, which will be increased by the addition of a third abbr:LIGO detector in India during the period where the main network is operating at design sensitivity.
  | Epoch                    | Estimated BNS Rate /yr |
  |--------------------------+------------------------|
  | Early                    | 0.15 - 3               |
  | Mid                      | 0.15 - 6               |
  | Late                     | 1 - 50                 |
  | Design                   | 4 - 80                 |
  | Design (abbr:LIGO India) | 11 - 180               |
  

* Strain
  The propagation of a gravitational wave will cause a relative displacement between free test masses in spacetime. As a result, a gravitational wave will produce a relative strain, perturbing the normal metric. In the far-field approximation the metric, $g_{\mu\nu}$ can thus be described 
\begin{equation}
\label{eq:strain-in-metric}
g_{\mu \nu} = \eta_{\mu \nu} + h_{\mu \nu},
\end{equation}
with the strain, $h_{\mu\nu}$ perturbing the underlying (potentially flat) metric $\eta_{\mu\nu}$.

The strain, as measured by a gravitational wave detector, can have two polarisation states, the "$+$" state and the "\times" polarisation state, which combine linearly,
\begin{equation}
\label{eq:gw-polarisations-strain}
h = A_{+} h_{+} + A_{\times} h_{\times}.
\end{equation}

Finally, the overall measured strain in a detector will be the superposition of both the strain signal and noise (which, is usually produced by movement of the detector's test masses due to effects other than spacetime perturbations). As such, the measured signal timeseries, $h(t)$, added to the noise timeseries $n(t)$ provides us with the total measured strain, $s(t)$,
\[ s(t) = n(t) + h(t). \]

** Characteristic strain
    The characteristic strain is intended to account for integrating an inspiralling signal, leading to a straight-forward relationship between the characteristic strain and the gls:snr.

#+ATTR_LATEX: :options [Characteristic strain]
#+BEGIN_definition
\begin{equation}
\label{eq:characteristic-strain}
 [h_{\text{c}}(f)]^{2} = 4 f^{2} \left| \tilde{h}(f) \right|^{2}
\end{equation}
#+END_definition

The noise can be treated similarly,
\begin{equation}
\label{eq:characterstic-noise}
\left[ h_{\text{n}}(f) \right]^{2} = f S_{\text{n}}(f).
\end{equation}
As noted by cite:strain.conventions this allows the integration of the strain compared to the noise budget of a given detector to be estimated "by eye", when displayed on a log-log plot.

** Power spectral density
** Amplitude spectral density

* Alternative theories of gravity
