# \chapterprecis{\Glspl{gw} were perhaps the last of the
#   predictions of Einstein's General Theory of Relativity to be
#   observed; their detection was the catalyst for the beginning of a
#   new era of astrophysics}

# \epigraph{I guess we need to do the detection checklist...}{\textbf{Sergey Klimencko}, \emph{Internal LSC communication}, 14 September 2015}

\lettrine[lines=3]{T}{he 14 September 2016} will likely be remembered as one of the most significant in the history of astronomy and of astrophysics. 
Early in the morning of this autumn day, shortly after 9am UT, a gravitational wave passed through the Earth, 
and on its way produced a sufficiently large movement in the mirrors and test masses of the detectors of the gls:ligo, as to be detected.

Over five months of data analysis, detector characterisation, and detection verification were conducted by a global team of scientists, in the gls:ligo and gls:virgo Scientific Collaboration (LVC). 
This process resulted in a slew of journal papers being written, vast quantities of data produced, and an enormous public outreach effort to be launched. 
Eventually, the collaboration found itself in a position to make the announcement of the first direct detection of gravitational waves, gls:gw150914, on 11 February 2016.

Further discoveries were made during the first observing run of the gls:aligo facilities, gls:lvt151012, observed in October, and gls:gw151226, observed in December, added to the menagerie of directly detected black hole binaries (although the significance of the former was insufficient to garner its own press release and announcement publication). 
The majority of 2016 was dedicated to introducing upgrades to the two gls:aligo interferometers, and to comissioning a third second-generation interferometric observatory, gls:virgo, located in Italy.
The second observation run of gls:aligo, which was scheduled to be longer and more sensitive than its first lead to the observation of three further binary black hole coalescences, gls:gw170104, gls:gw170608, and gls:gw170814, the latter observed by a network of three detectors, gls:virgo having joined the observing run a short time before.

gls:gw150914 is not the first evidence for gravitational waves, with the Hulse-Taylor pulsar cite:1975ApJ...195L..51H,2005ASPC..328...25W having provided compelling indirect evidence which lead to its
discoverers receiving the 1993 Nobel Prize.


* Gravitational Waves and General Relativity

Gravitational waves are one of the predictions of Einstein's 1915
Theory of General Relativity cite:1915SPAW.......844E, with the first
theoretical prediction of their existence being proposed by Einstein
in 1916 cite:1937FrInJ.223...43E,1918SPAW.......154E, less than a
year after the publication of the general theory, however research
work in this area remained largely stagnant until the 1960s, when
interest in the field picked-up


The Einstein field equations are non-linear, and analytical solutions
aren't possible. In order to perform calculations in general
relativity it is possible to turn to  \emph{post-Newtonian} expansion. 

The lowest-order expansion from which radiation is produced is the
quadrupole order, which depends upon the density and velocity field of
the system. The quadrupole tensor is defined

\begin{equation}
  \label{eq:1}
  Q_{jk} = \int \rho x_k x_k \frac{̣\dd^3}{\dd x^3}
\end{equation}
and the gravitational wave is described by the three-tensor
\begin{equation}
  \label{eq:2}
  h_{jk} = \frac{2}{r} \frac{̣\dd^2 Q_{jk}}{̣\dd t^2}
\end{equation}




* GW150914: The first detection

* GW170817: The first multi-messenger detection
