
/This chapter is composed principally from the method presented in cite:dw-sgrb-bayesian-contraint, with expanded discussion on the use of this method not only to estimate the average opening angle of GRB beams, but also its potential application to more general beamed emission./

* Short gamma-ray bursts and compact binary coalescences
#+NAME:sec:sgrbs

/An introduction to short gamma ray bursts should go here, which needs to be re-written compared to the discussion of SGRBs from the original paper, since that was written mainly by Andrew./

\begin{equation}
\label{eq:rate2angle}
    \grbrate = \epsilon\cbcrate \left \langle 1-\cos \theta \right \rangle,
\end{equation}

* From Rates To Beaming Angles
#+NAME:sec:grb-rate-to-beaming

In this section, we discuss our approach to estimating the abbr:sgrb beaming angle based on the binary neutron star inspiral rate, estimated through a number of abbr:gw observations of abbr:bns coalescence.
We demonstrate the approach by considering plausible detection scenarios for advanced abbr:ligo, which are summarised in table ref:tab:ratescenarios.
Our ultimate goal is to develop a generic approach that folds in uncertainties in the abbr:bns merger rate and our ignorance about the probability with which such mergers actually result in abbr:SGRB.

An overview of the general method is as follows:

1. Estimate the posterior probability distribution on the abbr:bns merger rate in the local universe from a number of observed gravitational wave signals and our knowledge of the sensitivity of the detectors. We construct a joint posterior distribution on the abbr:bns rate and the (unknown) probability $\epsilon$ that a given merger results in a abbr:sgrb. 

2. Use equation ref:eq:rate2angle, which relates the abbr:bns merger and abbr:sgrb rates via the geometry of the beaming angle, to transform the rate posterior probability to a posterior probability on the mean abbr:sgrb beaming angle.

3. Marginalize over $\epsilon$. We choose to consider $\epsilon$ a nuisance parameter because, to date, there is no accurate estimate of this parameter and it is not the main focus of our analysis. 


** Constructing The Rate Posterior
#+NAME:sec:grb-rate-posterior

Our goal is to infer the posterior probability distribution for the mean
abbr:SGRB beaming angle $\theta$ from abbr:GW constraints on the rate of \BNS
coalescence $\cbcrate$.  The core ingredient to the analysis is the posterior
probability distribution on the coalescence rate $p(\cbcrate|D,I)$, where $D$
represents some abbr:gw observation and $I$ denotes other unenumerated prior
information.  We will first demonstrate how $p(\cbcrate|D,I)$ may be constructed
for a few projected observing scenarios from~cite:Aasi:2013wya.  Later, in
section~\ref{sec:beaming_limits}, we will extend the analysis to place
limits on $\theta$ based upon the lack of detection during O1. Previously, a
comparison of rates was used to place a lower limit on the beaming angle
in cite:Abbott:2016ymx.

To form the posterior on the coalescence rate, we begin by constructing the
posterior on the \emph{signal} rate.  Note that these are not identical since
only those \BNS mergers which occur within a certain range yield a detectable
signal.  abbr:gw data analysis pipelines (e.g. {\tt
FINDCHIRP}~\cite{2012PhRvD..85l2006A}, {\tt
PyCBC}~\cite{Canton:2014ena,Usman:2015kfa,alex_nitz_2017_844934}) identify
discrete `candidate events' which are characterised by network \acp{SNR},
$\rho_c$, which, for the case of abbr:bns searches, indicate the similarity between
the detector data and a set of template abbr:bns coalescence waveforms.  The
measured rate $r$ of these events consists of two components: a population of
true abbr:gw signals, $s$; and a background rate, $b$, due to noise fluctuations
due to instrumental and environmental disturbances.

\begin{equation}
r = s + b
\begin{cases}
s = \text{signal rate} \\
b = \text{background rate}.
\end{cases}
\end{equation}

Typically for an all-sky, all-time analysis, like that described
in~\cite{Usman:2015kfa}, the significance of a candidate event is
empirically measured against `background' data representative of the
detector noise, which naturally varies from candidate to candidate.  A
detection requires this significance to be above some pre-determined
threshold (e.g. $5\sigma$ for GW150914 and
GW151226~\cite{Abbott:2016blz,Abbott:2016nmj}).  We follow the method
in~\cite{Aasi:2013wya}, which defines a detection as a candidate with
$\rho_c \geq 12$, corresponding approximately to
$b=10^{-2}$\,yr$^{-1}$.  Since the background rate $b$ is known, we
are just left with the problem of inferring the signal rate $s$.
Assuming a uniform prior on $s$ and a Poisson process underlying the
events, it may be shown (e.g.,~\cite{2010blda.book.....G}) that the
posterior for the signal rate, given a known background rate $b$ and
$n$ events observed over a time period $T$ is,

\begin{equation}
p(s|n,b,I) = C \frac{ T\left[(s+b)T\right]^n e^{-(s+b)T}}{n!},
\end{equation}

where,
\begin{eqnarray}
C^{-1} & = &\frac{e^{-bT}}{n!} \int_0^{\infty}\diff(sT)(s+b)^n T^n e^{-sT}\\
& = & \sum_{i=0}^n \frac{ (bT)^i e^{-bT}}{i!}.
\end{eqnarray}

Finally, we can transform the posterior on the \emph{signal} rate to
the underlying \emph{coalescence} rate via our knowledge of the
sensitivity of the abbr:gw analysis.  In particular, the signal
detection rate is simply the product of the intrinsic coalescence rate
$\cbcrate$ and the number of \BNS mergers which would result in a
abbr:gw signal with $\rho_c\geq12$.  Expressing the binary coalescence
rate in terms of the number of mergers per \ac{MWEG}, per year then we
require the number of galaxies $N_{\mathrm{G}}$ which may be probed by
the abbr:gw analysis.  At large distances, this is well approximated
by~\cite{rates_paper},

\begin{equation}
    N_G = \frac{4}{3} \pi \left( \frac{\dhor}{\mpc}
\right)^3 (2.26)^{-3} (0.0116),
\end{equation}

where $\dhor$ is the horizon distance (defined as the distance at which an
optimally-oriented \BNS merger yields $\rho_c\geq12$), the factor of 2.26
results from averaging over sky-locations and orientations, and
$1.16\times 10^{-2}$\,Mpc$^{-3}$ is the extrapolated density of \ac{MWEG} in
space.

Finally, the posterior on the binary coalescence rate $\cbcrate$ is obtained from a trivial transformation of the posterior on the signal rate $s$,

\begin{eqnarray}
    p(\cbcrate|n,T,b,\dhor) & = & p(s|n,T,b) \left|\frac{\diff s}{\diff \cbcrate}\right| \\
                                   & = & N_G(\dhor)p(s|n,T,b).
\end{eqnarray}

We see that in this approach, the rate posterior depends only on the
number of signal detections $n$, the observation time $T$, the
background rate $b$, and the horizon distance of the search $\dhor$.
It is precisely these quantities that comprise the detection scenarios
outlined in~\cite{Aasi:2013wya}.  Before constructing expected rate
posteriors, we outline the transformation from rate to beaming angle.

\subsection{Constructing the beaming angle posterior}
Inferences of the \ac{SGRB} beaming angle are made from the posterior
probability density on the beaming angle $p(\theta|D,I)$ where, as
usual, $D$ indicates some set of observations and $I$ unenumerated
prior knowledge.  Our goal is to transform the measured posterior
probability density on the rate $\cbcrate$ to a posterior on the
beaming angle.

First, note that we can express the joint distribution
$p(\theta, \epsilon|D,I)$ as a Jacobian transformation of the joint
distribution $p(\cbcrate, \epsilon|D,I)$:
\begin{equation}
p(\theta,\epsilon) = p(\cbcrate,\epsilon)
\left\lvert\left\lvert
\frac{\partial(\cbcrate,\epsilon)}{\partial(\theta,\epsilon)}
\right\rvert\right\rvert,
\end{equation}

where we have dropped conditioning statements for notational convenience.
The Jacobian determinant can be  computed from equation~\ref{eq:rate2angle}.
It is then straightforward to marginalize over $\epsilon$ to yield the posterior on $\theta$ itself:

\begin{eqnarray}
    \label{eq:beam_posterior}
    p(\theta) & = & \int_{\epsilon} p(\theta,\epsilon)~\diff \epsilon\\
              & = & \int_{\epsilon} p(\cbcrate,\epsilon)
    \left\lvert\left\lvert
    \frac{\partial(\cbcrate,\epsilon)}{\partial(\theta,\epsilon)}
    \right\rvert\right\rvert~\diff \epsilon \\
              & = & \frac{2\grbrate \sin
\theta~p(\cbcrate)}{(\cos\theta-1)^2}\int_{\epsilon}
\frac{p(\epsilon)}{\epsilon} ~\diff \epsilon,
\end{eqnarray}

where we have assumed $\epsilon$ and $\cbcrate$ are logically independent such that,
\begin{equation}
p(\epsilon,\cbcrate) = p(\epsilon|\cbcrate)p(\cbcrate) = p(\epsilon)p(\cbcrate).
\end{equation}

It is important to note that the entire procedure of deriving the jet
angle posterior is completely independent of the approach used to
derive the rate posterior.  In the preceding section we adopted a
straightforward Bayesian analysis of a Poisson rate which is amenable
to a simple application of plausible future detection scenarios; there
is no inherent requirement to use that method to derive the rate
posterior.

Given the posterior on the rate, $p(\cbcrate)$, the final ingredient
in this approach is the specification of some prior distribution for
$\epsilon$. Given the lack of information on the value and distribution
of $\epsilon$, we choose three plausible priors and study their effects
on our beaming angle inference. Our choice of priors are:

\begin{description}
\item [Delta-function] $p(\epsilon) = \delta(\epsilon=0.5)$;
        the probability that \BNS mergers yield \acp{SGRB} is known to be 50\%
        exactly.

\item [Uniform] $p(\epsilon)=U(0,1)$;
        the probability that \BNS mergers yield \acp{SGRB} may lie anywhere
    $\epsilon \in (0,1]$ with equal support in that range. 

    \item [Jeffreys] $p(\epsilon)=\beta(\frac{1}{2},\frac{1}{2})$; treating the
        outcome of a \BNS merger as a Bernoulli trial in which a \ac{SGRB}
        constitutes `success' and $\epsilon$ is the probability of that success,
        the least informative prior, as derived from the square root of the
        determinant of the Fisher information for the Bernoulli distribution, is
        a $\beta$-distribution with shape parameters $\alpha=\beta=\frac{1}{2}$.
\end{description}

\section{Prospects For Beaming Angle Constraints With Advanced LIGO}
We now demonstrate the derivation of the rate posterior $p(\cbcrate)$
and the subsequent transformation to the beaming angle posterior
$p(\theta)$.  We consider four abbr:gw observation scenarios with
\ac{aLIGO} based on the work in~\cite{Aasi:2013wya}.  An observing
scenario essentially consists of an epoch of \ac{aLIGO} operation,
which defines an expected search sensitivity (i.e., \BNS{} horizon
distance $\dhor$) and observation time $T$; as well as an assumption
on the rate of \BNS{} coalescence in the local universe $\cbcrate$.
Each observing scenario ultimately results in an expectation for the
number of observed \acp{GW} from \BNS coalescences.  For this study,
we assume the `realistic rate' for $\cbcrate$ as described
in~\cite{rates_paper}.

Our first goal is to establish the expected number of detections in
each scenario.  Given the observation time and horizon distance of the
observation epoch we first compute the 4-volume accessible to the
analysis,
%
\begin{equation}
    \label{eq:search_volume}
    V_{\mathrm{search}} = \frac{4}{3}\pi \left(\frac{\dhor}{2.26}\right)^3 \times \gamma T,
\end{equation}

where the factor 2.26 arises from averaging over source sky location
and orientation, $T$ is the observation time and $\gamma$ is the
\emph{duty cycle} for the science run.  Following~\cite{Aasi:2013wya},
we take $\gamma=0.5$.  For comparison, during the first observing run
of \ac{aLIGO}, the two interferometers observed in coincidence
achieving $\gamma_{\mathrm{coinc}} = 0.41$.  Where there is a range in
the horizon distances quoted in~\cite{Aasi:2013wya} to account for
uncertainty in the sensitivity of the early configuration of the
detectors, we use the arithmetic mean of the lower and upper bounds
when computing the search volume.  Table~\ref{tab:scenarios} lists
the details of each observing scenario.

\begin{table}
\centering
\begin{tabular}{lccccc}
  \toprule
  Epoch &  $T$ & \dinsp & $V_{\mathrm{search}}$ & Est. \BNS \\
        &   [yr] & [Mpc] & [$\ee{6} \mpc³\,\yr^{-1}$] & Detections \\
  \colrule
  2015--2016 & 0.25 & 40--80   & 0.05--0.4 & 0.0005--4 \\
  2016--2017 & 0.5 & 80--120 & 0.6--2.0 & 0.006-20\\
  2018--2019 & 0.75 & 120--170 & 3--10 & 0.04--100\\
  2020+      & 1    & 200 & 20 & 0.2--200 \\
  2024+      & 1    & 200 & 40 & 0.4--400 \\
  \botrule
\end{tabular}
\caption{Advanced detector era observing scenarios considered in this
  work.  $T$ is the expected duration of the science run and $\dinsp$
  is the \BNS inspiral distance for the sensitivity expected to be
  achieved at the given epoch, which is equal to $\dhor / 2.26$.
  $V_{\mathrm{search}}$ is the sensitive volume of the search, defined
  by equation~\ref{eq:search_volume}; the final column contains the
  estimated range of the number of abbr:gw detections.  Note that the
  quoted search volume accounts for a network duty cycle of
  $\sim 80\%$ per detector.  These scenarios are derived from those detailed
  in~\cite{Aasi:2013wya}. While the 2020+ and 2024+ scenarios appear
  identical in terms of the sensitivity of the detectors, the 2024+
  scenario includes a third advanced LIGO detector in India. This
  expansion of the network is expected to lead to an increase in the
  network duty cycle, and an increase in the area of the sky which the network is sensitive to, resulting in a greater volume being searched per
  year.
  \label{tab:scenarios}}
\end{table}


\subsection{Posterior Results}
Figure~\ref{fig:aligorate} shows the \BNS rate posteriors resulting
from the observations in the scenarios in table~\ref{tab:scenarios}
generated using the procedure described in
section~\ref{sec:rate_posterior}. Where a range of potential inspiral
distances is given for a scenario we choose the median value, so for
the 2015--2016 scenario we take \dinsp{} to be $60\,\mpc$, for
example. Likewise we choose an illustrative value of $n$, the number
of expected abbr:gw detections, from each range; these are listed in
table \ref{tab:rateposteriors}.

We now use these posteriors together with the prior distributions
described in section~\ref{sec:rate_posterior} and the observed rate of
\acp{SGRB} (as described in section~\ref{sec:sgrbs}, we use
$\grbrate=10$\,Gpc$^{-3}$yr$^{-1}$~\cite{Nakar:2007yr,Dietz:2010eh})
to derive the corresponding beaming angle posteriors.

\begin{figure}
\centering
{\includegraphics[width=\linewidth]{figures/rate_posteriors_violin.pdf}}
\caption{Posterior probability distribution for the rate of \BNS
    coalescence assuming the scenarios in table \ref{tab:scenarios}.
    The 95\% credible interval is represented with a horizontal line through
    the centre of the plot, with vertical lines delineating the lower and upper limits; the median is represented by a square marker, and the
    maximum \latin{a posteriori} (\ac{MAP}) value is denoted by a diamond. A
    summary of these values is given in table \ref{tab:rateposteriors}.
    \label{fig:aligorate} }
\end{figure}


\begin{table}
\begin{center}
  \begin{tabular}{lrrrrr}
    \toprule
    Scenario &    $n$ & Lower       & MAP             & Median          & Upper\\
             &        & [$\yr^{-1}$] & [$\yr^{-1}$]    & [$\yr^{-1}$]    & [$\yr^{-1}$]  \\
    \colrule
    2015--2016 & 0   & 0.00	 & 0.45	 & 2.80	 & 11.98	\\
    2016--2017 & 1   & 0.17	 & 4.07	 & 6.74	 & 19.13	\\
    2017 -- 2018 & 3 & 1.37	 & 5.88	 & 6.99	 & 15.26 \\	
    2020+ & 10 &7.30	 & 14.47	 & 15.25	 & 25.25	\\
    2024+ & 20 & 12.42	 & 20.35	 & 20.65	 & 30.09	\\
    \botrule
\end{tabular}
\end{center}

\caption{Summary of the \BNS rate posteriors for each of the observing
  scenarios which are considered in this work; these posteriors are plotted
  in figure \ref{fig:aligorate}. Here $n$ is the number of abbr:gw events which were assumed to be observed in each scenario, chosen from the ranges in table \ref{tab:scenarios}.
  \label{tab:rateposteriors}
}
\end{table}

\subsubsection{Validation}
\label{sec:validation}
Before we derive beaming angle posteriors corresponding to the
aforementioned observing scenarios, it is useful to establish some
form of validation for our procedure.  This validation is performed by
first selecting values of the beaming angle, the \ac{SGRB} efficiency,
and the rate of \BNS coalescence.  We choose $\theta=10^{\circ}$, and
the `realistic' \BNS rate $\cbcrate = 10^{-6}$\,Mpc$^{-3}$yr$^{-1}$.
We then compute the value of the \ac{SGRB} rate that would correspond
to these parameter choices.  Finally, we simply use this
\emph{artificial} value for $\grbrate$ in
equation~\ref{eq:beam_posterior} when we compute the posterior on the
beaming angle, with the understanding that the resulting posterior
should yield an inference consistent with the `true' value
$\theta=10^{\circ}$.

\begin{figure}
\centering
\includegraphics[width=\linewidth]{figures/O1_injections_violin.pdf}
\caption{ In order to validate the algorithm an artificial scenario
  was constructed with a known beaming angle by artificially setting a
  GRB rate of $36.7\, \yr^{-1}$ to induce a beaming angle of $\theta \approx 10^{\circ}$.
  The algorithm was then tested with the various priors used in the
  analysis,  using
  the same horizon distance, observing time, and duty cycle as the 2015--2016
  observing scenario. to ensure that the correct beaming angle was inferred. 
  These posteriors are based on the simulated 2015--2016 observing scenario (see
  table~\ref{tab:scenarios}).
  \label{fig:injjetposterio2016}}
\end{figure}

\begin{table}
  \centering
  \begin{tabular}{lrrrr}
    \toprule
    Prior & Lower & MAP & Median & Upper\\
          & [$^\circ$] & [$^\circ$]& [$^\circ$]& [$^\circ$] \\
    \colrule
    $\delta(1.0)$ & 3.68	 & 5.88	 & 8.45	         & 39.44	 \\
    $\delta(0.5)$ & 5.24	 & 8.59	 & 11.89	 & 50.51	 \\
    Jeffreys      & 4.38	 & 7.69	 & 13.23	 & 69.74	 \\
    U(0,1)        & 4.62	 & 8.14	 & 13.23	 & 63.81	 \\
    \botrule
\end{tabular}
\caption{Summary of the beaming angle posteriors from figure
  \ref{fig:injjetposterio2016}, for the 2015--2016 observing scenario,
  with an artificial GRB rate imposed to produce a target beaming
  angle of $\theta = 10^{\circ}$.
  \label{tab:summaryinj2015}}
\end{table}

\begin{figure}
\centering
\includegraphics[width=\linewidth]{figures/O2_injections_violin.pdf}
\caption{The procedure used to produce figure \ref{fig:injjetposterio2016} was repeated for the observing time and the horizon distance of the 2016--2017 observing scenario, with a GRB rate of $28.0 \,\yr^{-1}$ used to induce a beaming angle of $\theta \approx 10^{\circ}$.
  \label{fig:injjetposterio2017}}
\end{figure}
\begin{table}
  \centering
  \begin{tabular}{lrrrr}
    \toprule
    Prior & Lower & MAP & Median & Upper\\
          & [$^\circ$] & [$^\circ$]& [$^\circ$]& [$^\circ$] \\
    \colrule
    $\delta(1.0)$ & 4.15	 & 6.78	 & 7.62	 & 21.17	 \\
    $\delta(0.5)$ & 6.11	 & 9.50	 & 10.88	 & 27.88	 \\
    Jeffreys & 5.05	 & 9.05	 & 12.21	 & 62.72	 \\
    U(0,1) & 5.12	 & 9.05	 & 11.29	 & 51.04	 \\
    \botrule
\end{tabular}
\caption{Summary of the beaming angle posteriors from figure
  \ref{fig:injjetposterio2017}, for the 2016--2017 observing scenario,
  with an artificial GRB rate imposed to produce a target beaming
  angle of $\theta \approx 10^{\circ}$.}
  \label{tab:summaryinj2016}
\end{table}

%
Figures~\ref{fig:injjetposterio2016} and~\ref{fig:injjetposterio2017}
show the beaming angle posteriors which result from this analysis for
the 2015--2016 and 2016--2017 scenarios respectively for each choice
of prior distribution on the efficiency parameter.  Unsurprisingly,
the most accurate constraints arise when we already have the tightest
possible constraints on the \ac{SGRB} efficiency, $\epsilon$.  That
is, the beaming angle posterior arising from the $\delta$-function
prior on $\epsilon$ is the narrowest, yielding the shortest possible
credible interval.  It is well worth remembering, however, that had
we been incorrect regarding the value of $\epsilon$ when using the
$\delta$-function prior, the result would be significantly biased and
our inference on the beaming angle would be incorrect.  This
highlights the necessity of building a suitable representation of our
ignorance into the analysis.  Finally, we note that the results from
the uniform and Jeffreys distribution priors are broadly equivalent.


\subsubsection{Jet Angle Posteriors From Observing Scenarios}

\begin{figure}
\centering
{\includegraphics[width=\linewidth]{O1_beaming_posteriors_violin.pdf}}
\caption{Beaming angle posteriors using different priors on \ac{SGRB} efficiency $\epsilon$ in the 2015--2016 observing scenario.
    \label{fig:jetposterior2016}}
\end{figure}

\begin{figure}
\centering
{\includegraphics[width=\linewidth]{O2_beaming_posteriors_violin.pdf}}
\caption{Beaming angle posteriors using different priors on \ac{SGRB} efficiency $\epsilon$ in the 2016--2017 observing scenario.
    \label{fig:jetposterior2017}}
\end{figure}

Figures~\ref{fig:jetposterior2016} and~\ref{fig:jetposterior2017} show
the beaming angle posteriors obtained for two of the detection
scenarios.\footnote{
    A note on implementation: rather than directly evaluating
    the beaming angle posterior in equation~\ref{eq:beam_posterior} we
    choose to sample points from the posterior using a Markov-Chain
    Monte-Carlo algorithm, implemented using the python package
    \texttt{PyMC3}~\cite{salvatier2016probabilistic}.
}\footnote{
    While we present the entire posterior for only these two
    observing scenarios in this section, we provide an overview of all
    of the observing scenarios in section~\ref{sec:future}.}
Since it is a common assumption in related literature, we also now include
a prior on the \ac{SGRB} efficiency which dictates that all \BNS produce a
\ac{SGRB}, $p(\epsilon|I)=\delta(\epsilon=1)$, as well as our previous
strong $\delta$-function prior.  For the 2016-2017 scenario where
inferences are somewhat weak (i.e., broad posteriors) due to the
sparsity of abbr:gw detections, the uncertainties are large enough
that the results from each prior are broadly consistent.  In the 2024+
scenario, where the posterior is more peaked, it is clear that the
strong $\delta$-function priors lead to inconsistent inferences on the
\ac{SGRB} beaming angle.  The much weaker uniform and $\beta$
distributions, by contrast, are again largely consistent with each
other yielding more conservative and robust results, as well as being
a more representative expression of our state of knowledge.  The
inferences drawn from each scenario and each prior are summarised in
terms of the maximum \emph{a posteriori} measurement and the 95\%
credible interval around the maximum in
table~\ref{tab:aligo_beam_inference}.
