The astrophysical sources of gravitational waves can be divided
roughly into three categories cite:2009LRR....12....2S

+ Continuous :: sources are expected to produce radiation
  constantly, or at least over long periods of time. The primary
  source of continuous sources for gls:aLIGO are expected to be
  gravitational wave pulsars, but in detectors which are sensitive at
  lower frequencies, such as the proposed gls:LISA mission, the radiation
  from inspiralling binary systems should also be detectable.
+ Transient :: sources produce a strong \emph{burst} of
  gravitational waves over a period of seconds or less. These are
  sources which are primarily expected in the advanced LIGO passband,
  with compact binary coalesences and supernovae being major targets
  for burst searches in the advanced observing runs, however there are
  prospects for burst sources in the gls:LISA regime, for example from
  hyperbolic encounters between compact objects and stars or other
  compact objects
  cite:2012PhRvD..86l4012B,2012PhRvD..86d4017D,2008MPLA...23...99C,2008APh....30..105C,2010MmSAI..81...87D,2005PhRvD..72h4009G,2010PhRvD..82j7501B,2011ApJ...729L..23G.
+ Stochastic :: sources are expected to produce a background of
  gravitational waves, from the black holes at the centres of
  galaxies cite:1980Natur.287..307B,2001astro.ph..8028P,2003ApJ...583..616J,2008MNRAS.390..192S,
  and from the universe's inflationary period cite:1988PhRvD..37.2078A.


# \sidebar{
\begin{figure}
     \input{figures/cbc_spectrum.pgf}
     \caption{The frequency spectrum of a compact binary coalescence, alongside the power spectrum of the advanced LIGO detector.
     \label{fig:cbcₛpectrum}}
\end{figure}
#     \captionof{figure}{The frequency spectrum of a compact binary coalescence, alongside the power spectrum of the advanced LIGO detector.}
#     } 

** Compact Binary Coalescences

  A pair of orbiting objects can also produce gravitational waves, and
  as they do so their orbit loses energy, causing the radius of the
  orbit to shrink cite:1995PhRvL..74.3515B. The objects spiral in
  towards each other. This behaviour has already been observed in the
  Hulse-Taylor
  pulsar cite:1975ApJ...195L..51H,2005ASPC..328...25W, a system
  of two neutron stars---one of which is a pulsar--- which, through
  precise pulsar timing measurements, have been inferred to be
  inspiralling, and producing gravitational waves.

  The binary system will continue to lose energy via gravitational radiation until it reaches its /innermost stable circular orbit/, after which the objects will merge, and eventually coalesce. 
These coalescence events are powerful sources of gravitational waves, and the chirp produced by the coalescence may be sufficiently luminous to be detected by current, advanced detectors. 
Attempts to detect signals from such coalescing systems were also made during the initial run of the detectors cite:2012PhRvD..85h2002A.
These would be characterised by the distinct pattern of the pseudo-sinusoidal inspiral waveform, followed by a bright burst of radiation, and then a sinusoidal ``ringdown'' as the post-coalescence remnant vibrates\cite{2009LRR....12....2S}. 
Binary coalescences are thus
  classified as transient, or burst sources.

The potential objects which may be involved in an observable binary
coalescence are black holes and neutron stars: both compact
objects. White dwarf binaries may also be observable, and these
systems are expected to be much more abundant than either neutron star
or black hole binaries, but their emission lies within the passband of
gls:LISA---a planned space-based gravitational wave observatory. These
never reach a last stable orbit, as it lies within their physical
diameter, and so the inspiral component of the waveform is the
principle source of gravitational waves. These are expected to be so
numerous in [[abbr:LISA]] results cite:2013GWN.....6....4A that entirely new statistical methods will be
needed to process the observations, and to allow observations of other
phenomena to be made in their background.

[[abbr:smbbh]] are believed to collide and merge as part of the merging processes of galaxies. 
Again these binaries should produce signals within the passband of [[abbr:LISA]] cite:2012CQGra..29l4016A, 
and should be so spectacuarly strong that they are visible in the [[abbr:LISA]]
data without the \emph{matched filtering} techniques which are required to extract other signals from the data cite:2009LRR....12....2S. 
The observation of these objects would provide much-needed information about the evolution of galaxies and of super-massive black holes.

Inspiralling compact binaries can act as a cosmological distance measure: 
they have two parameters, their period, and the rate at which that period changes (which is calculated by measuring the gls:chirp-mass of the system) which characterise the system, and the
amplitude of the gravitational waves produced is dependent only on the
chirp mass of the source, and the distance from the observer to the
object. As a result it is possible to determine the distance to an
inspiralling system simply by determining the chirp mass and measuring
the brightness of the event. This would provide an additional means of
measuring cosmic acceleration, and, in the LISA era, this would allow
the measurement of acceleration at high redshift using high-mass
binary black holes.
