/This chapter is broadly a mixture of introductory material regarding astrophysical sources of gravitational waves, the waveforms which those sources are expected to produce, and the models and simulations which are required to produce them. This should stand as a motivation for the material presented later in this work regarding the production of statistical surrogate models. The final sections of this chapter will focus on the need for and production of mock data challenges, their role in testing detection and analysis pipelines, and the development of a consistent infrastructure to support this task./

The astrophysical sources of gravitational waves can be divided roughly into three categories cite:2009LRR....12....2S

+ Continuous :: sources are expected to produce radiation   constantly, or at least over long periods of time. 
  The primary source of continuous sources for gls:aLIGO are expected to be gravitational wave pulsars, but in detectors which are sensitive at lower frequencies, such as the proposed gls:LISA mission, the radiation from inspiralling binary systems should also be detectable.
+ Transient :: sources produce a strong /burst/ of gravitational waves over a period of seconds or less. The sources of transient signals are normally further sub-divided. /Unmodelled/ sources, where there are insufficient theoretical models to use matched filtering techniques to search for signals in detector data. /Modelled/ sources, which currently encompass abbr:cbc sources are sufficiently well understood, in contrast, to allow the use of this powerful analysis technique. These are sources which are primarily expected in the advanced LIGO passband, with compact binary coalesences and supernovae being major targets for burst searches in the advanced observing runs, however there are prospects for burst sources in the gls:LISA regime, for example from hyperbolic encounters between compact objects and stars or other compact objects  cite:2012PhRvD..86l4012B,2012PhRvD..86d4017D,2008MPLA...23...99C,2008APh....30..105C,2010MmSAI..81...87D,2005PhRvD..72h4009G,2010PhRvD..82j7501B,2011ApJ...729L..23G. 
+ Stochastic :: sources are expected to produce a background of gravitational waves, from the black holes at the centres of galaxies cite:1980Natur.287..307B,2001astro.ph..8028P,2003ApJ...583..616J,2008MNRAS.390..192S, and from the universe's inflationary period cite:1988PhRvD..37.2078A.

* Compact Binary Coalescences

#+NAME:fig:cbc_spectrum
#+CAPTION: The frequency spectrum of two types of compact binary coalescence—a binary neutron star coalescence, and a binary black hole coalescence—alongside the design sensitivity power spectrum of the Advanced LIGO detector at its design sensitivity. *Should update this to use the IMRPhenom frequency line*.
[[./figures/sources/aligo-cbc.pdf]]

The moment of inertia tensor of a two-body system will lead to non-spherical motion within the system, which will in turn produce gravitational radiation, and gradual orbital decay cite:1995PhRvL..74.3515B. 
This effect was first observed in the Hulse-Taylor pulsar cite:1975ApJ...195L..51H,2005ASPC..328...25W, a system containing two neutron stars---one of which is a pulsar--- which, through precise pulsar timing measurements, were been inferred to be  inspiralling, and producing gravitational waves. This observation was the first strong, indirect evidence for the reality of gravitational wave production.

The binary system will continue to lose energy via gravitational radiation until it reaches its /innermost stable circular orbit/, after which the objects will merge, and eventually coalesce. 
These coalescence events are powerful sources of gravitational waves, and the chirp produced by the coalescence may be sufficiently luminous to be detected by current, advanced detectors. 
Attempts to detect signals from such coalescing systems were also made during the initial run of the detectors cite:2012PhRvD..85h2002A.
These would be characterised by the distinct pattern of the pseudo-sinusoidal inspiral waveform, followed by a bright burst of radiation, and then a sinusoidal ``ringdown'' as the post-coalescence remnant vibrates\cite{2009LRR....12....2S}. 
Binary coalescences are thus classified as transient, or burst sources.

The potential objects which may be involved in an observable binary
coalescence are black holes and neutron stars: both compact
objects. White dwarf binaries may also be observable, and these
systems are expected to be much more abundant than either neutron star
or black hole binaries, but their emission lies within the passband of
gls:lisa---a planned space-based gravitational wave observatory. These
never reach a last stable orbit, as it lies within their physical
diameter, and so the inspiral component of the waveform is the
principle source of gravitational waves. These are expected to be so
numerous in gls:lisa results cite:2013GWN.....6....4A that entirely new statistical methods will be
needed to process the observations, and to allow observations of other
phenomena to be made in their background.

gls:smbbh are believed to collide and merge as part of the merging processes of galaxies. 
Again these binaries should produce signals within the passband of gls:lisa cite:2012CQGra..29l4016A, 
and should be so spectacuarly strong that they are visible in the gls:lisa
data without the \emph{matched filtering} techniques which are required to extract other signals from the data cite:2009LRR....12....2S. 
The observation of these objects would provide much-needed information about the evolution of galaxies and of super-massive black holes.

Inspiralling compact binaries can act as a cosmological distance measure: they have two parameters, their period, and the rate at which that period changes (which is calculated by measuring the gls:chirp-mass of the system) which characterise the system, and the amplitude of the gravitational waves produced is dependent only on the chirp mass of the source, and the distance from the observer to the object. 
As a result it is possible to determine the distance to an inspiralling system simply by determining the chirp mass and measuring the brightness of the event. 
This would provide an additional means of measuring cosmic acceleration, and, in the gls:LISA era, this would allow the measurement of acceleration at high redshift using high-mass binary black holes.


** Dynamics of compact binaries
   :PROPERTIES:
   :CUSTOM_ID: sec:sources:cbc:dynamics
   :END:


   The dynamics of binary systems are well-understood in Newtonian mechanics, where the two-body problem can be reduced to a pair of independent one-body problems. 
In contrast no exact solutions have been found to this problem in abbr:gr; while the Schwarzschild solution *cite* is sufficient for some situations where the mass of one of the two bodies is much smaller than the other (where the problem is effectively a single one body problem) it is insufficient for systems such as abbp:bbh.

When the two component bodies of the system are at large separation (and their local velocities are much smaller than the speed of light) a abbr:pn expansion can be used.
In this regime the two objects are treated as point-particles with slow internal dynamics. 
In such a post-Newtonian system, the parameter $\epsilon$, defined as 
\begin{equation}
	\epsilon = \max\left\{ \left| \frac{ \tensor{T}{^{0i}}}{\tensor{T}{^{00}}} \right|,
                              \left| \frac{ \tensor{T}{^{ij}}}{\tensor{T}{^{00}}} \right|^{1/2},
			      \left| \frac{ U }{c²} \right|^{1/2} 
		       \right\},
\end{equation}
(with $U$ the Newtonian potential in the system) must be much less than one cite:2014LRR....17....2B.
Through an abuse of notation this term is normally written as $\epsilon \equiv 1/c$ [fn:pn-epsilon].
The abbr:pn correction to the Newtonian limit on the order $\mathcal{O}(1/c^{n})$ is generally called the $(n/2)$-abbr:pn order.

*More work is needed on this, but this is rather heavy lifting stuff.*

As a first-order approximation the amplitude of a gls:GW from an inspiralling compact binary system can be approximated as cite:strain.conventions
\begin{equation}
  \label{eq:cbcinspiral}
  h_{\text{c}}(f) = 
\end{equation}
where $f$ is the frequency of the gravitational wave, and $\dot{f}$ its time derivative.

*Tidal effects in NS systems*

[fn:pn-epsilon] With $1/c$ /not/being dimensionless.


** The compact binary waveform
   :PROPERTIES:
   :CUSTOM_ID: sec:sources:cbc:waveform
   :END:

   *figure: It would be good to have a plot of a waveform here with some cartoons of each period overlaid.*

   The gravitational waveform for a compact binary system can be split into three broad periods, which are each associated with the dominant energy loss mechanisms within the system. 
The first, and longest stage of the binary's evolution is the /gls:inspiral/. Gravitational radiation carries energy out of the binary system, causing the orbit to slowly decay.[fn:generalbinary] 
For the majority of the inspiral the gravitational waves produced have a very low amplitude, and are to weak to be detected by the current generation of detectors, however this amplitude increases as the radius of the orbits decrease.
Eventually this amplitude becomes observable, for a period ranging from minutes (in the case of abbr:bns events *cite gw170817*), to fractions of a second (for most abbr:bbh events *cite gw150914*).

As the binary reaches its innermost stable circular orbit the system evolves from the inspiral period to the merger.
At this point the two black holes /plunge/ towards each other, and then coalesce. 
This period contains the peak emission of abbp:gw. 

Finally, the single black hole which remains will radiate energy through the /gls:ringdown/ period, during which the black hole oscillates, radiating energy until it becomes a stable Kerr black hole.

[fn:generalbinary] This in fact occurs in /all/ orbits, however most objects will not get close enough that the current generation of detectors will be able to observe the low-amplitude radiation produced by such systems. In the future, however, inspirals of objects such as white dwarf binaries are expected to be noise sources for space-based detectors, such as gls:lisa.

** Numerical relativity 
   :PROPERTIES:
   :custom_id: sec:sources:cbc:nr
   :END:

The study of compact binary systems using gravitational waves relies on solving the relativistic two-body problem; the classical, Newtonian solutions to this problem are Keplerian orbits, however post-Newtonian gravity requires that a mass with orbital angular momentum loses energy in the form of gravitational waves; as such there are no stable solutions of the (general) relativistic two body problem.

The field of abbr:nr, while now capable of producing accurate waveforms for a wide variety of initial abbr:bbh conditions, had a lengthy period of development. 
As recently as 1999 Brügmann cite:1999IJMPD...8...85B notes that "the binary black hole problem is essentially unsolved".
The major stumbling-blocks for abbr:nr were specific to abbr:gr. 
The first of these, the gauge freedom of the theory, which generally makes specifying a numerical coordinate grid on the simulated spacetime impossible in advance.
As a result an effective method of producing such a coordinate grid during the evolution of the numerical simulation must be employed, which avoids the introduction of coordinate singularities.
Coordinate singularities represented the second major challenge to the field; in the case of abbr:bbh spacetimes these are typical features. 
Additionally, finding a formalism for the representation of the field equations throughout the evolution of the simulation which would remain stable had proved challenging.

By the mid-2000s a number of breakthroughs occured. 
In 2004 Pretorius cite:2005CQGra..22..425P introduced the "generalised harmonic coordinate" formalism which remained stable into the evolution of the abbr:BBH merger.
This was followed cite:2005PhRvL..95l1101P by the demonstration of an abbr:nr simulation which evolved the abbr:bbh through the inspiral and merger to the ringdown produced in this formalism.
Late in 2005 Campanelli et al. cite:2006PhRvL..96k1101C demonstrated the use of an algorithm which overcame the difficulties of coordinate singularities inherent in black hole simulations.
These had previously been overcome through the "excission" of the black hole, where a boundary was placed inside the black hole event horizon, excising its interior, containing the singularity, from the computational domain.
Instead, their technique employed "punctures", where the poles which represented the black holes were factored-out analytically, allowing the production of accurate and complete waveforms.
Also in 2005 Baker et. al cite:2006PhRvL..96k1102B developed a technique for extracting the abbr:bbh waveform directly from the outer region of the simulation, based on the work of Fiske et. al. cite:2005PhRvD..71j4036F.

The covariant nature of the abbp:efe makes choosing a frame of reference in which to evaluate the metric difficult, and complicates the process of defining an initial value problem to solve.
To get around this the abbp:efe are often decomposed into a (3+1)-dimensional foliation, in which the dynamics at each time slice can be solved.
A large range of scales must be resolved within abbr:nr simulations in order to model both the behaviour of spacetime close to the merging system and at the location that the gravitational wave is extracted. 
This range of scales makes evolving an abbr:nr simulation computationally burdensome, even with techniques such as adaptive mesh refinement which aim to make this process efficient. 
A recent review by Lehner and Pretorius cite:2014ARA&A..52..661L of the techniques involved in running abbr:nr simulations summarises a number of the techniques which are used to make abbr:nr tractable.


The complexity of abbr:nr simulations has lead to their adoption of parallelisation technology for multiprocessing and message-passing between processes, however these simulations can still require around a month to produce on computing clusters containing thousands of processors. 

*** SpEC
    The abbr:spec is a abbr:nr method which leverages spectral methods during the evolution of the black hole spacetime in abbr:bbh simulations, in an attempt to circumvent instabilities which are present when using finite difference methods cite:2000PhRvD..62h4032K. 
The code is capable of generating the merger and ringdown component of the abbr:gw waveform for a generic abbr:bbh configuration cite:2009PhRvD..80l4010S.

*** BAM
    The abbr:bam code uses a modified abbr:bssn regime. cite:2004PhRvL..92u1101B,2008PhRvD..77b4027B,2004PhRvL..92u1101B,1999IJMPD...8...85B

*** Einstein Toolkit & MAYA
    The gls:maya code is based on the abbr:bssn formalism with a moving puncture gauge condition.

*** Georgia Tech Waveform catalogue
    The Georgia Tech waveform catalogue cite:2016CQGra..33t4001J is composed of 452 waveforms which were generated using the gls:maya abbr:nr code at the Centre for Relativistic Astrophysics at Georgia Institute of Technology.
The catalogue includes both non-spinning simulations for quasi-circular systems with mass-ratios $q \leq 15$, and precessing quasi-circular systems with $q \leq 8$. 
Within the set of waveeforms derived from spinning systems are two subsets: aligned-spin, where the spin axis of each black hole is parallel to the orbital angular momentum, $\vec{L}$; and precessing, where the spin axes are not parallel to $\vec{L}$. The distribution of abbr:bbh parameters for the waveforms in the cataloue are plotted in the corner plot of figure ref:fig:sources:cbc:nr:gtcoverage.

\begin{figure}
\caption{The coverage of the Georgia Tech catalogue. \label{fig:sources:cbc:nr:gtcoverage}}
\includegraphics{figures/gt-coverage.pdf}
\end{figure}

*** SXS waveform catalogue
    cite:2013PhRvL.111x1104M
*Should include detail about the different codes which are used for GT and SXS*

** Analytical approximants
   :PROPERTIES:
   :custom_id: sec:sources:cbc:approximants
   :END:
   
   The impossibility of producing enough abbr:nr waveforms to densely cover even the two dimensional parameter space of non-spinning abbr:bbh systems has lead to the development of algorithms capable of producing approximations of the waveform across the parameter space.
   While abbr:pn approximants provide a powerful approximation to the waveform in the gls:inspiral phase, as the characteristic velocity of the binary approaches the speed of light the abbr:pn expansion will lose accuracy, and an alternative method for approximating the waveform around the merger is required. 
   There are currently two major implementations of such approximants; the gls:imrphenom family, and the gls:seobnr family of approximants.

*** IMRPhenom
    :PROPERTIES:
    :CUSTOM_ID: sec:sources:cbc:approximants:imrphenom
    :END:


   The gls:imrphenom models take advantage of the three-component structure of abbr:bbh signals (see ref:sec:sources:cbc:waveform); calibration waveforms for the models are produced by a abbr:nr simulation, which is then hybridised with a abbr:pn inspiral waveform (since the abbr:pn is known to be a good approximation for this part of the waveform).
For hybridisation to be effective the abbr:pn and abbr:nr waveforms must be well-matched. 
This match is determined by their integrated squared absolute difference, 
\begin{equation}
\delta = \int_{t_{1}}^{t_{2}} \left| \ten{h}^{\text{PN}}(t, \vec{\mu}) - a \ten{h}^{\text{NR}}(t, \vec{\mu}) \right|^{2} \dd{t}
\end{equation}
with $\ten{h}^{\text{NR}}$ an abbr:nr-derived waveform, $\ten{h}^{\text{PN}}$ a abbr:pn waveform evaluated at the same parameters, $a$ is an amplitude scaling factor, and $\vec{\mu}$ a vector of extrinsic parameters, $\vec{\mu} = {\phi_{0}, t_{0}}$, the initial phase and start time of the waveform, respectively cite:2008PhRvD..77j4017A.

The resulting hybridised waveforms are then parameterised in the Fourier domain. 
These /phenomenological/ waveforms, $u(f)$ take the form
\begin{equation}
\label{eq:source:cbc:imrphenoma}
u(f) = A(f) \exp(i \Psi(f) )
\end{equation}
for $\Psi$ the phase, and with a piecewise function describing the amplitude, $A$ as a function of frequency, $f$:
\begin{equation}
\label{eq:sources:cbc:imrphenoma:amp}
A(f) = C
\begin{cases}
(f/f_{\text{merge}})^{-7/6} & \text{if} f < f_{\text{merge}} \\
(f/f_{\text{merge}})^{-2/3} & \text{if} f_{\text{merge}} < f < f_{\text{ring}} \\
w \mathcal{L}(f, f_{\text{ring}}, \simga) & \text{if} f_{\text{ring}} < f < f_{\text{cut}} \\
\end{cases}
\end{equation}
where $f_{\text{merge}}$, $f_{\text{ring}}$, and $f_{\text{cut}}$ are respectively the initial merger frequency, initial ringdown frequency, and the cutoff frequency of the template. $\mathcal{L}$ is a Lorenzian distribution of width $\sigma$, and $w$ is a normalisation constant which describe the quasi-normal mode frequencies, and $C$ is a numerical constant (details of these parameters, and the stationary phase approximation expansion which is used for $\Psi$ can be found in cite:2008PhRvD..77j4017A).

The amplitude and phase parameters of these phenomenological waveforms are then determined by fitting the model to around thirty hybridised waveforms. 
Finally, the best-matching amplitudes and phases for the phenomenological waveforms are fitted to the physical parameters of the binary in order to produce a physically parameterised model.

The first model to take this approach, IMRPhenomA, was calibrated only against non-spinning hybrid waveforms. Further development produced the IMRPhenomD model cite:2016PhRvD..93d4007K, which is calibrated against 19 hybrid abbr:pn-abbr:nr waveforms (a mixture of public SXS and BAM-derived waveforms) to produce aligned-spin spinning waveforms. The IMRPhenomD model is then verified against 29 additional hybrid waveforms. 

The IMRPhenomP series of waveform models (the most recent of which is version 3 cite:2018arXiv180910113K) add the ability to model precession effects within the waveform; for versions 1 and 2 this was limited to single-spin effects, but version 3 has been designed to allow for generic abbr:bbh systems.
In order to introduce the effects of precession into the waveform, IMRPhenomPv1 and IMRPhenomPv2 built on the non-precessing waveforms from the IMRPhenomC and IMRPhenomD families, respectively, and then added the "twisting-up" produced by orbital precession.
For these first two versions the precession angles were calculated by a frequency-domain expression which assumed a single-spin system, under the stationary phase approximation[[ fn:stat-phase]], which is not strictly valid outwith the inspiral phase.
IMRPhenomPv3 uses a two-spin model developed by Chatziioannou et al. cite:2017PhRvD..95j4004C in order to allow for the calculation of precession angles in generic abbr:bbh systems.

In summary:
   + IMRPhenomA :: The simplest of the IMRPhenom models, designed to produce waveforms for non-spinning, non-precessing systems.
   + IMRPhenomD :: The successor to the IMRPhenomB and IMRPhenomC models, designed to produce waveforms for spinning, non-precessing systems.
   + IMRPhenomPv3 :: A model capable of producing generically spinning, precessing waveforms.

*** Effective one-body   
    :PROPERTIES:
    :CUSTOM_ID: sec:sources:cbc:approximants:eob
    :END:

An alternative approach to the phenomenological fitting of the gls:imrphenom algorithms is the abbr:eob approach.
The abbr:eob approach cite:1999PhRvD..59h4006B,2000PhRvD..62f4015B,2009arXiv0906.1769D maps the dynamics of two compact objects into that of a single test particle moving in a deformed Kerr metric.
In contrast to the piecewise approach to building the waveform taken in the gls:imrphenom model (see section ref:sec:sources:cbc:approximants:imrphenom), the abbr:eob approach constructs the entire waveform in a single process cite:2011PhRvD..84l4052P. 
The waveform is constructed by assuming that the merger is short but with a broad range of frequencies; this section of the waveform is built by attaching the signal from a plunge signal to quasinormal modes.

Similarly to gls:imrphenom, the abbr:eob derived waveforms are calibrated against a number of abbr:nr derived waveforms. 
For the non-spinning model, \texttt{EOBv2} this involved five waveforms produced by the \texttt{SPEC} code.

+ EOBNRv1 :: This was the prototype abbr:eob approximant. 4-abbr:pn corrections to the abbr:eob radial potential, calibrated between $q = 1$ and $q=4$. It is a non-spinning approximant. cite:2007PhRvD..76j4049B
+ EOBNRv2 :: A non-spinning calibrated between $q=1$ and $q=6$. Uses four sub-leading EOB modes.   cite:2011PhRvD..84l4052P
+ SEOBNRv1 :: cite:2012PhRvD..86b4011T
+ SEOBNRv2 :: cite:2014PhRvD..89f1502T
+ SEOBNRv3 :: cite:2014PhRvD..89h4006P
+ SEOBNRv4 :: cite:2017PhRvD..95d4028B

[[fn:stat-phase]] The stationary phase approximation is found to provide sufficient accuracy for the matched-filtering processes which are common in abbr:gw data analysis. cite:1999PhRvD..59l4016D

** Numerical relativity surrogate models

   Recently, an entirely different approach to approximating the abbr:bbh waveform has started to emerge, based on /surrogate modelling/.
These models attempt to directly model abbr:nr waveforms without introducing phenomenological assumptions, or approximations to abbr:gr, and take what might be considered a /data-driven/, or statistical approach to the problem. 
While the ability to abandon these assumptions and approximations is attractive, it comes at the expense of requiring a large number of abbr:nr waveforms with which to condition the model.
To date, there have been two approaches to building such models: those using spline regression, and those using /Gaussian process regression/. 
This section will contain a broad overview of the former, but a thorough discussion of the latter will be given later in this work (in chapter cha:gaussian-process).

*** Spline surrogate models

    The NRSur family of surrogate models, developed by Blackman /et al./ cite:2015PhRvL.115l1102B,2017PhRvD..95j4023B,2017PhRvD..96b4058B employ spline interpolation to waveforms generated by the SpEC abbr:nr code.
The two analysis-ready versions of this model, NRSur4d2s and NRSur7d2s are capable of producing waveforms for systems with a mass-ratio $<2$ and an effective spin-parameter $< 0.8$. 
In contrast to phenomenological models, the NRSur models are currently capable of producing only a small number of cycles of the waveform, being limited by the length of the abbr:nr waveforms off which they are conditioned.
Recent efforts have been made, however, to produce similar surrogate models which are conditioned on hybridised waveforms cite:2018arXiv181207865V.
The number of waveforms required to produce the surrogate model is also considerably larger than thise requqired for the phenomenological models, with NRSur7d2s being conditioned on 744 abbr:nr waveforms.

+ Prototype :: A non-spinning model capable of producing waveforms between $q=1$ and $q=20$. cite:2015PhRvL.115l1102B
+ NRSur4d2s :: The first production-ready surrogate model, which was capable of modelling waveforms with $q<2$ and effective spin parameters $< 0.8$. cite:2017PhRvD..95j4023B
+ NRSur7d2s :: A generically spinning surrogate model cite:2017PhRvD..96b4058B.

*** Gaussian process surrogate models

+ DOCTOR :: A prototype non-spinning model trained on IMRPhenomPv2-derived waveforms.
+ HERON :: A prototype, fully precessing waveform model trained using waveforms from the Georgia Tech catalogue.

* Continuous wave sources
# It's very weird; right now as I'm writing parts of this chapter I'm in the same lecture theatre as Bell. 2019-02-27 (JimFest).
The discovery of pulsars by Bell and Hewish in 1967 was an unexpected discovery for radio astronomy---objects which produce beams of radiation, and rotate rapidly, like a lighthouse. 
Not long after their discovery it became apparent that they were a specific form of abpl:ns---the tightly-packed remnant of a massive star which has ended its life as a supernova.

Any rotating mass quadrupole (see equation ref:eq:intro:gr:mass-quadrupole) will produce gravitational waves as it rotates (see equation ref:eq:intro:gr:quadrupole2strain), and so it follows that a dense, massive object, such as a neutron star, will produce gravitational waves as they rotate, if they possess any mass asymmetry.
Further, thanks to their highly stable rotation speed, the abbr:gw emission from abpl:ns ought to be produced continuously at a very stable frequency.
As gravitational wave emission occurs in the quadrupole [(2,2)] mode [fn:gr-quadrupole], this emission should be at twice the rotational frequency of the abbr:ns.

The rotation frequency of most pulsars is well-measured by radio observations, making these attractive prospective sources for ground-based abbr:gw detectors, such as gls:ligo and gls:virgo. 
Indeed, targetted searches for abpl:gw from pulsars at twice their rotation frequency have been conducted since the "initial" detector period, using data from gls:ligo, gls:geo600, and later gls:virgo (which are summarised in cite:2014ApJ...785..119A), and continued into the advanced era cite:2017ApJ...839...12A.

Pulsar spins are known to decelerate over time, through a process known as spin-down. 
This process is often attributed to energy loss through gravitational radiation. 
The spin-down limit of a pulsar is the abbr:gw strain which corresponds to this scenario, where the entirity of the energy being lost is radiated as abbr:gw, and is defined as
\begin{equation}
\label{eq:sources:cw:spindown}
h = \left( \frac{5}{2} \frac{G I_{zz} | \dot{f} | }{c^{3} d^{2} f } \right)
\end{equation}
for a pulsar with a spin frequency $f$, moment-of-inertia tensor $I$, at a distance $d$ from the observer.

To date no continuous abbr:gw source has been detected, but the failure to measure gravitational waves from known pulsars has allowed tight limits to be placed on the ellipticity of 222 known radio pulsars cite:2019arXiv190208507T, with the tightest limit that placed on J$0711-6830$, at $1.2\ee{-8}$. 
# The latest results, from the analysis of the first two observing runs' data from advanced gls:ligo, show that the slow-down of the Crab pulsar cannot be explain

Searches made for pulsars at around twice their rotation frequency were augmented with targetted searches for emission at the rotation frequency following the second observing run cite:2019arXiv190208507T. 
This is possible if the rotating neutron star is either biaxial or triaxial, and exhibits free precession. 
Emission at the rotation frequency may also be possible in abpl:ns with pinned superfluid interiors cite:2010MNRAS.402.2503J.

Continuous wave searches can also be used to test abbr:gr, and to place limits on the parameters of alternative theories of gravity. 
Searches for non-tensorial polarisations of abbr:gw were conducted on data from the first advanced observing run cite:2018PhRvL.120c1104A for all six potential polarisations allowed in general metric theories. 

In comparison to transient signals, the waveforms for continuous wave sources are generally (semi-)analytical; the waveform model used for the search for the (2,2)-mode emission in cite:2019arXiv190208507T for example has the form 

\begin{equation}
\label{eq:sources:cw:signalmodel}
\begin{align}
h_{22}(t) = - C_{22} \big[ & F_{+}^{D}(\alpha, \delta, \psi, t) (1 + \cos^{2} \imath) \cos(2 \Phi(t) + \Phi_{22}^C) \\
+ 2 & F_{\times}^{D} (\alpha, \delta, \psi, t) \cos \imath \sin( 2 \Psi(t) + \Psi_{22}^{C} )
\big] 
\end{align}
\end{equation}
for $C_{22}$ the amplitude of the wave, and $\Psi_{22}^{C}$ its initial phase at some specific time.
$\Phi(t)$ is the rotational phase of the source, and $\imath$ is the inclination of the source to the observer.
In contrast to the signal from transient sources, continuous waves can be observed over long periods of time, and the observed signal will be convolved with the antenna pattern of the detector, $F_{+,\times}^{D}$, which varies with the sky position of the source, $(\alpha, \delta)$, the polarisation angle of the source, and thanks to the relative movement of the source and the detector, time, $t$.

[fn:gr-quadrupole] In general relativity, at least.

* Stochastic backgrounds

In addition to transient and continuous sources of abpl:gw, which originate from specific locations in the sky, we expect that a /background/ of abpl:gw should be observable throughout the sky (with an approximately isotropic distribution). The abbr:gw background is expected to cover the entire frequency range at some level, from extremely low frequencies (around an inverse Hubble-time) to frequencies exceeding $\SI{10^{14}}{\hertz}$.

The abbr:gw background is approximately analogous to the abbr:cmb.
This is the near-isotropic electromagnetic emission discovered in 1964 as constant background radio emission across the sky, which originates from the epoch of recombination, when atoms started to form, and the universe became optically thin. 

Since we expect that this background would be continuous and isotropic, it is likely to fall into the part of the measured abbr:gw data which is treated as noise by the majority of analyses.
The noise produced by the detector will be greater than this signal, and so detection of a background is also reliant on correlations between a network of detectors.
This reliance on correlations between a network of detectors significantly affects the sensitivity of the detector network to background sources cite:PhysRevD.88.124032. 
*It might be nice to include a plot related to this, especially if this is coded-up in grasshopper.*
   
   The level of anisotropy in the abbr:cmb implies that the universe today must be very-nearly flat, and since any curvature would increase as the universe undergoes metric expansion, this would suggest that the early universe was even flatter.
This poses a dilemma, as a flat universe requires the energy density of the universe to be equal to a critical energy density, with a small deviation becoming exagerated over time. 
Inflation is an attempt to address this problem, by suggesting that the universe expanded extremely rapidly early in its evolution, through the effect of some scalar field.
Such a scalar field would be subject to quantum fluctuations, and tensor fluctuations would be expected to produce gravitational waves cite:1988PhRvD..37.2078A. 
abbr:gw production is not predicted in the early universe by non-inflationary models, and so discovery of an inflationary abbr:gw background would be strong evidence for the inflation model cite:2016arXiv160501615C.
   
   First-order phase transitions, which occur when the thermodynamic properties of a system are discontinuous (such as the sudden, discontinuous change in the entropy and volume of a liquid as it boils) could also be responsible for the production of abpl:gw in the early universe.
A number of phase transitions are believed to have occured as, for example, the strong and electroweak forces decoupled cite:2016JCAP...04..001C.

Cosmic strings may also be a viable source of background radiation. 
These are topolgical defects which are caused by symmetry phase transitions in a number of grand unified theories. 
As these defects move they interact with each other to form kinks and cusps, which can be the source of bursts of gravitational radiation.
Over a sufficiently long period the signals from these events can superimpose to form apart of the abbr:gw background.

The inspiral of the very large number of compact binary systems in the universe will also superimpose to contribute to this background radiation. 
These systems include galactic white dwarf binaries, which are expected to produce such a strong signal that they will limit the sensitivity of the gls:lisa detector, as well as abbr:bbh and abbr:bns systems.

Searches for a stochastic background have been made using the data from the advanced gls:ligo detectors during their first observing run cite:PhysRevLett.118.121101.
To date no evidence of a background have been identified, which has allowed an upper limit to be placed on its strength. 
Additional limits have been placed thanks to astrometric measurements of active galactic nuclei using radio data and the first GAIA data release cite:2018ApJ...861..113D, and through pulsar timing arrays cite:2015MNRAS.453.2576L,PhysRevLett.115.041101. 

* Unmodelled and poorly modelled transient sources
  :PROPERTIES:
  :CUSTOM_ID: sec:source:burst
  :END:
  
** Burst waveform models
   :PROPERTIES:
   :CUSTOM_ID: sources:burst:models
   :END:


   \begin{figure}
   \caption[A catalogue of unmodelled burst waveforms]{The three unmodelled burst ``waveforms'' which are typically considered by burst analyses; Gaussian-like bursts, Sine-Gaussian bursts, and White noise bursts. 
   The first row depicts each of these waveforms in the time domain, with both the plus polarisation (red) and cross polarisation (blue) depicted.
   The second row contains the time-frequency spectrogram of each waveform in the plus polarisaiton.
   The third row contains the time-frequency constant-$q$ transform of each waveform.
   \label{fig:sources:burst:adhoc}
   }
   \includegraphics[width=\textwidth]{figures/sources/minke-adhoc.pdf}
   \end{figure}	

*** Parameterisation

    While signals from well-defined astrophysical systems, such as abbr:cbc signals, can be parameterised according to the intrinsic and extrinsic properties of the generating system, burst signals do not have a well-defined physical model.
    As a result we must define a number of parameters based purely on the properties of the signal.

    The first of these is the /Characteristic squared amplitude/, $|| h^{2} ||$.

    #+BEGIN_definition
    The characteristic squared amplitude, $|| h^{2} ||$, is defined as
    \begin{equation}
    || h^{2} || = \int_{\infty}^{\infty} | h(t)|^{2} \dd{t} =  \int_{\infty}^{\infty} | \tilde{h}(f) |^{2} \dd{f},
    \end{equation}
    for $h(t)$ and $\tilde{h}(f)$ respectively the strain in the time, $t$, and frequency $f$ representations.
    #+END_definition

    For bursts which are well-localised in time we can also define a central time and a duration.
    
    
*** Sky position
    

*** Gaussian

    Perhaps the simplest conceivable model of a burst of abpl:gw is one where energy is emitted across a broadband range of frequencies over a fixed period of time, with a smooth rise and decay in amplitude.
    Such a source can be modelled as with a Gaussian function, and may be a suitable model for broadband sources, such as the core-bounce during a core-collapse abbr:sn.

    In searches the model for such a signal is
    \begin{equation}
    \label{eq:sources:burst:waveforms:gaussian}
    h(t) = A \exp\left( - \frac{ (t - t_{0})^{2} }{ 2 \sigma^{2} } \right)
    \end{equation}
    for a strain $h$ at time $t$, with an amplitude $A$, central time $t_{0}$ and duration $\sigma$.

    An example of a Gaussian burst ($\sigma = \SI{0.01}{\second}$, $A = 1\ee{-21}$, and $t_{0} = \SI{100}{\second}$) is plotted in the left column of figure ref:fig:sources:burst:adhoc, with the time-domain waveform in the first row. 
    In this figure the two polarisations of the signal are plotted, with only the plus polarisation containing abbr:gw power for this morphology. 
    The second and third rows contain time-frequency representations of the waveform as a spectrogram and a constant $q$-transform, respectively.

*** Sine-Gaussian
    In addition to searching for broadband, time-constrained bursts of abbr:gw energy, some sources are expected to produce abpl:gw which are in a confined range of frequencies, in addition to being released over a short time-span. 
    Such a source can be approximated by a sinusoidal signal which is enveloped by a Gaussian rise and decay in amplitude.
    The model used in gls:ligo searches for such signals is: 
    \begin{equation}
    \label{eq:sources:burst:sinegaussian}
    h(t) = A \exp \left( \frac{ - 2(t - t_{0})^{2} \pi^{2} f^{2}}{Q^{2}} \right) \cos\left( 2 \pi f (t - t_{0}) \right),
    \end{equation} 
    for a strain $h$ at time $t$, with $A$ the amplitude of the signal, $t_{0}$ its central time, $Q$ the quality factor of the burst, and $f$ is frequency.

    An example of a sine-Gaussian burst ($q = 8$, $f = \SI{100}{\hertz}$, $A = 1\ee{-21}$, and $t_{0} = \SI{100}{\second}$, with linear polarisation) is plotted in the middle column of figure ref:fig:sources:burst:adhoc, with the plus- and cross-polarised time-domain waveforms in the first row. 
    The second and third rows contain time-frequency representations of the waveform as a spectrogram and a constant $q$-transform, respectively.

*** White noise bursts
    :PROPERTIES:
    :CUSTOM_ID: sources:burst:models
    :END:
    Astrophysical processes are unlikely to produce emission at a single frequency, or with a smooth evolution of amplitude, and so searches are normally expected to be sensitive to band-limited white noise bursts, which consist of band-limited uncorrelated noise within a Gaussian amplitude envelope.
    An example of a whitenoise burst (with duration $\SI{0.05}{\second}$, $f = \SI{1000}{\hertz}$, $A = 1\ee{-21}$, and $t_{0} = \SI{100}{\second}$, with linear polarisation) is plotted in the right column of figure ref:fig:sources:burst:adhoc, with the plus- and cross-polarised time-domain waveforms in the first row. 
    The second and third rows contain time-frequency representations of the plus-polarisation waveform as a spectrogram and a constant $q$-transform, respectively.


*** Ringdown-like bursts
    Ringdown-like signals, with a sudden rise, and exponential decay in amplitude are expected in the post-merger signal of abbr:cbc systems, and in some models of neutron star model excitation cite:2004PhRvD..70l4015B. These take the form
    \begin{equation}
    \label{eq:sources:burst:ringdown}
    h(t) = \exp (t / \tau) \sin( 2 \pi f t)
    \end{equation}
    for a strain $h$ at time $t$, given a decay time $\tau$ and frequency $f$.


** Parabolic and hyperbolic encounters
   :PROPERTIES:
   :CUSTOM_ID: sources:burst:encounters
   :END:

   Encounters between pairs of black holes, where the two bodies trajectories are affected by the total gravitational field, but where a closed orbit is not formed are expected to be possible in regions of space with a high density of compact objects, for example globular clusters and the centres of galaxies.
   In the case where the deflection angle of the trajectories is small this process can be considered analogous to bremsstrahlung processes in electromagnetic radiation production cite:PhysRevD.1.1559,1978ApJ...224...62K, but the emission production becomes more complicated as larger deflection angles are considered, and spin is included.
   Approximate models are available for the waveforms of these encounters in the bremmstrahlung case, 
   low-velocity cases with arbitrary deflection cite:1977ApJ...216..610T, and head-on collisions cite:1992PhRvD..46..694D. 
   Recent advances have allowed the production of 3.5 abbr:pn accurate waveforms for hyperbolic encounters for non-spinning pairs of black holes cite:2018PhRvD..98b4039C

   Recent advances in abbr:nr modelling have allowed the production of accurate waveforms for parabolic encounters between spinning black holes, and in section ref:sources:burst:encounters:waveforms I consider the detectability of some of these waveforms in current and future detectors.

*** Encounter waveforms
    :PROPERTIES:
    :CUSTOM_ID: sources:burst:encounters:waveforms
    :END:
    
    #+CAPTION: The abbr:snr of a $q=16$ hyperbolic encounter waveform in advanced abbr:ligo at design sensitivity.
    [[./figures/hyperbolic-m16-l024.pdf]]


** Supernovae

*** Core-collapse supernovae

#+CAPTION: Core-collapse supernova spectrum.
#+NAME:fig:ccsn-spectrum
[[./figures/sources/source-ccsn.pdf]]

 Core collapse supernova (CCSNe) are driven by the release of
 gravitational energy as a massive star's core collapses. Progenitor
 stars of CCSNe have zero-age-main-sequence (ZAMS) masses in the range
 $8\,\msolar \leq M \leq 130\,\msolar$. Much of this energy is stored as
 heat in the protoneutron star remnant, around 99% of the released energy
 is carried-off by neutrinos, around 1% provides the kinetic energy of
 the explosion, while less than $0.01\%$ of the energy is extracted as
 electromagnetic and gravitational radiation \cite{2009CQGra..26f3001O}.

 When the iron core of a star exceeds the Chandrasekhar mass it becomes
 unstable, and undegoes gravitational collapse, and is compressed until
 the neutron degeneracy pressure is able to halt arrest the collapse. At
 this point the core becomes stiff, and the inner core rebounds---a phase
 of the supernova known as "core bounce". The stiff, ultra-dense remnant
 of the collapse is a proto-neutronstar (PNS).

 Gravitational waves are expected to be emitted in a number of periods
 during the collapse, for example during a rotating collapse, and the
 core-bounce which follows it; pulsations of the PNS
 \cite{1966ApJ...145..514M}; and anisotropic neutrino emission
 \cite{1979ApJ...231Q.644E,1978ApJ...223.1037E,1978Natur.274..565T}.

 In order to predict the gravitational waveforms which would be produced
 by a CCSN detailed numerical modelling must be completed, with the most
 modern results from Scheidegger, modelling rotating, axisymmetric
 collapses in three dimensions, and Dimmelmeier\cite{2008PhRvD..78f4056D}
 in two dimensions; and Müller and Ott\cite{2013ApJ...768..115O},
 modelling neutrino-driven supernovae in three dimensions.

 It is possible that core-collapse supernovae could have been detected
 with the initial LIGO detector\cite{2009LRR....12....2S}, although none
 were. At design sensitivity the three-detector network of Advanced LIGO
 and Advanced VIRGO should be able to detect CCSNe to a distance of
 around $\SI{5.5}{\kilo pc}$, in the case of neutrino-driven explosions,
 while rapidly-rotating core-collapses will be detectable to
 $\SI{50}{\kilo pc}$, the distance to the Large Magellanic Cloud. Extreme
 emission scenarios may be detectable as far as $\SI{0.77}{\mega pc}$,
 the distance to M31\cite{2016PhRvD..93d2002G}.

*** Type Ia supernovae

#+NAME:fig:T1a-spectrum
#+CAPTION: Type-1A supernova spectrum.
[[./figures/sources/source-t1asn.pdf]]

 Type Ia supernovae (SNe Ia) are believed to be the result of
 white-dwarfs in binary systems accreting enough matter to exceed the
 Chandrasekhar-mass, and undergoing catastrophic
 core-collapse\cite{2013MNRAS.429.1156S}, however the evolution of the
 binary systems which are the progenitors of Type Ia supernovae is poorly
 understood. Recent work\cite{2015PhRvD..92l4013S} implies that the
 gravitational wave emission from a Type Ia supernova would produce
 decihertz gravitational-waves, peaking at a frequency around . This
 would position SNe Ia as a target for the proposed DECIGO and BBO
 space-based observatories.
*** Supernova waveform models    

** Cosmic strings

   Cosmic strings are theorised topological defects which were first postulated by Kibble in 1976 cite:1976JPhA....9.1387K.
   These are expected to have been produced as a result of phase transitions in the early universe, and carry large quantities of energy.
   The simplest string models are characterised by the energy density of the string $\mu$, and its tension, which are taken to be equal.
   The dimensionless quantity $G\mu \sim (T_{\text{c}} / M_{\text{Pl}})^{2}$, with $G$ Newton's gravitational constant, $T_{\text{c}}$ the temperature at the transition, and $M_{\text{Pl}}$ the Planck mass, characterises the strength of interactions between strings.
   For strings produced by the decoupling of the strong force from the electroweak force this quantity has a value on the order of $10^{-6}$, so a quantity $\mu_{6}$ is often defined as a shorthand cite:1995RPPh...58..477H.

   Three seperate models of cosmic strings have been searched for in data from the advanced gls:ligo detectors to date, and while no evidence for abbr:gw emission from these objects was found, it was possible to place limits both on the parameters of the various models and on the scale of $G \mu$.
The gls:ligo results place a limit of $G \mu < 8.5\ee{-10}$, which agrees, but is surpassed by results from pulsar timing arrays, which find $G \mu < 5.7\ee{-12}$ cite:2018PhRvD..97j2002A.
*If the O2 paper is published in time, update this with the new results.*
   

# ** Accretion disk instability and long bursts



* Burst searches

Burst searches cannot rely on well-known template waveforms in the way that compact binary searches can, and so matched filtering techniques cannot be used.
Instead burst searches, similarly to searches for the stochastic background, make use of information gained from correlations between detectors in a network.

There are two approaches to analysing data across a network of detectors: 
   + coherent analysis :: combines the data steams of detectors together into a single stream, with all of the data analysed in the same process;
   + coincident analysis :: performs a search for signals on each detector's data separately, providing a list of times at which a candidate signal (or "trigger") is identified. These are then compared, allowing for suitable time delays corresponding to the wave travel time between detectors in the network, to identify coincident events.

The coherent method is substantially more difficult to perform, and can require access to greater computational resources than the simpler, faster coincident method. 
However, the coincident method is generally less sensitive, as a signal which is weakly detected in one detector, but strongly in another may not produce triggers in both analyses, where a coherent analysis would help to identify the more weakly-detected signal.

Initial abbr:ligo searches were performed both between the detectors constituting the abbr:ligo network (the two 4-km detectors in Louisiana and Washington, in addition to the 2-km detector in Washington), and between this network and gls:tama, gls:geo600, and gls:auriga. 

\begin{figure}

\centering
\begin{tikzpicture}[]

%\draw[help lines,step=5mm,gray!20] (0,0) grid (4,3);

\begin{scope}

\fill [red!40] (-2,0.8) rectangle (10,-0.6);
\fill [green!40] (-2,-0.6) rectangle (10,-3.2);
\fill [blue!40] (-2,-3.2) rectangle (10,-5.2);

\node (signal) {$h$};
 
\begin{scope}[below of = signal, anchor = north, xshift=-2 cm]
 \foreach \x in {1,..., 3} {
 	\node (convolution\x) at (\x, 0) { $\otimes$};
	\draw (signal.south) -- (convolution\x.north);
	\node  at (\x-0.3, 0) {$F_{\x}$};

	\node (xi\x) at (\x, -1) {$\xi_{\x}$};
	\draw(convolution\x.south) -- (xi\x.north);

	\node (addition\x) at (\x,-2.3) { $\oplus$};
	\draw (xi\x.south) -- (addition\x.north);
	\node at (\x-0.3, -2.3) {$N_{\x}$};

	\node (s\x) at (\x, -3.6) {$s_{\x}$};
	\draw (addition\x.south) -- (s\x.north);
	
}
\end{scope}
\end{scope}

\begin{scope}[xshift=5cm, every node/.style={text width=7cm}]

\node (signal-text) at (0,0) {A signal, $h$ is generated by an astrophysical source.};
\node (convolution-text) at (0, -2cm) {The signal is convolved with each detector's antenna pattern, $F$. \\ This gives the \emph{antenna response}, $\xi$.};

\node (addition-text) at (0, -4) {The signal, combined with noise, $N$, from the detector, giving the \emph{observed signal}, $s$.};

\end{scope}

\end{tikzpicture}

\caption{The construction of the abbr:gw signal observed by a network of detectors, from the abbr:gw source through to its measurement by a detector. \label{fig:sources:burst:signalflow}}

\end{figure}

** Fundamental search methods
   :PROPERTIES:
   :CUSTOM_ID: sec:sources:burst:searchmethods
   :END:
   + Power filter :: Calculates a weighted spectrogram of the data by splitting the whitened detector data into overlapping chunks.  cite:2004CQGra..21S.815G
   + Kleine Welle ::  The abbr:kw method uses either a wavelet or a Q-transform approach to produce a time-frequency representation of the measured signal. This is then thresholded, and clusters of outlier pixels (discrete regions of the time-frequency plane) are identified. By performing a number of Q-transforms with varying $q$ parameters it is possible to estimate the parameters of the detected waveform cite:2004CQGra..21S1809C.
   + Mean filter :: The mean filter is a time-series approach to burst detection, which searches for excesses in the moving average of the measured signal. The method is most sensitive to bursts which have a similar length to the moving window, so the search must be repeated for a number of different window lengths.

   + Null stream
   + Excess energy
		      

** Seach pipelines

While the fundamental methods described in section ref:sec:sources:burst:searchmethods are plausible methods for identifying burst signals in data, they are unable to operate in isolation. 
This has lead to the need to construct /pipelines/ which are capable of pre-processing the detector data, performing searches to produce lists of potential events (triggers), estimate the significance of these triggers, and perform parameter estimation on the signals. 
There are at least four major pipelines in use during the advanced detector runs.

\begin{figure}

\begin{tikzpicture}[]

%\draw[help lines,step=5mm,gray!20] (0,0) grid (4,3);

\begin{scope}

\fill [red!40] (-2,0.8) rectangle (10,-0.6);
\fill [green!40] (-2,-0.6) rectangle (10,-3.2);
\fill [blue!40] (-2,-3.2) rectangle (10,-5.2);

\fill [yellow!40] (-2,-5.2) rectangle (10,-8.2);

\fill [orange!40] (-2,-8.2) rectangle (10, -13);

\node (signal) {$h$};
 
\begin{scope}[below of = signal, anchor = north, xshift=-2 cm]
 \foreach \x in {1,..., 3} {
 	\node (convolution\x) at (\x, 0) { $\otimes$};
	\draw (signal.south) -- (convolution\x.north);
	\node  at (\x-0.3, 0) {$F_{\x}$};

	\node (xi\x) at (\x, -1) {$\xi_{\x}$};
	\draw(convolution\x.south) -- (xi\x.north);

	\node (addition\x) at (\x,-2.3) { $\oplus$};
	\draw (xi\x.south) -- (addition\x.north);
	\node at (\x-0.3, -2.3) {$N_{\x}$};

	\node (s\x) at (\x, -3.6) {$s_{\x}$};
	\draw (addition\x.south) -- (s\x.north);

	\node [circle, fill] (segment\x) at (\x, -4.5) {};
	\draw (s\x.south) -- (segment\x.north);

	\node [circle, fill] (whiten\x) at (\x, -5.5) {};
	\draw (segment\x.south) -- (whiten\x.north);

	\node [circle, fill] (delay\x) at (\x, -6.5) {};
	\draw (whiten\x.south) -- (delay\x.north);

	\node [circle, fill] (tf\x) at (\x, -8) {};
	\draw (delay\x.south) -- (tf\x.north);

	\node [circle, fill] (excess\x) at (\x, -9.5) {};
	\draw (tf\x.south) -- (excess\x.north);
	
}

	\node [rectangle, fill, minimum width=1cm] (significance) at (2, -11) {};

	\draw [bend left] (excess1.south) -- (significance.north);
	\draw [bend left] (excess2.south) -- (significance.north);
	\draw [bend left] (excess3.south) -- (significance.north);


	\node [circle, fill] (triggers) at (2, -12.5)  {};
	\draw (significance.south) -- (triggers.north);

	

\end{scope}
\end{scope}

\begin{scope}[xshift=6cm, every node/.style={text width=7cm}]

\node (signal-text) at (0,0) {A signal, $h$ is generated by an astrophysical source.};
\node (convolution-text) at (0, -2cm) {The signal is convolved with each detector's antenna pattern, $F$. \\ This gives the \emph{antenna response}, $\xi$.};

\node (addition-text) at (0, -4) {The signal, combined with noise, $N$, from the detector, giving the \emph{observed signal}, $s$.};

\node (segment-text) at (0,-5.7) {The recorded signals are split into segments.};
\node (segment-text) at (0,-6.7) {A filter is applied to whiten the data.};
\node (segment-text) at (0,-7.7) {Each detector signal is time-delayed with respect to a given sky location.};

\node (tf-text) at (0,-9.3) {The data from each detector is converted to a time-frequency representation.};
\node (excess-text) at (0,-10.8) {Pixels with excess power are identified, and clusters of these pixels are identified.};

\node (significance-text) at (0, -12.2) {The significance of the clusters are calculated jointly using the data from all detectors.};

\node (trigger-text) at (0, -13.7) {A list of triggers is produced, which can be sorted by significance, and thresholded.};

\end{scope}



\end{tikzpicture}

\caption{The principles of a coherent all-sky burst search pipeline.
	     \label{fig:sources:burst:coherentsearch}
}

\end{figure}


   + X-Pipeline :: X-Pipeline is designed to run coherent triggered searches for abbr:gw bursts, motivated by the detection of events such as abpl:sgrb cite:2010NJPh...12e3034S. The analysis constructs time-frequency spectrograms of the plus and cross strain polarisations, and the gls:null-stream, after they have been whitened and time-shifted. Pixels in the spectrograms are then clustered in order to identify significant outliers from the noise. This process is repeated for each location on the sky being searched, with appropriate time-shifts, for each detector's data. Events are vetoed if they have a strong correlation between the coherent energies and incoherent energies, a feature which indicates a noise glitch rather than a burst signal. The X-Pipeline can be combined with the SphRad pipeline to run all-sky, untargetted searches cite:maxfayesthesis in the XSphRad configuration.

#   + spherical radiometer 
   + Coherent WaveBurst :: The abbr:cwb pipeline cite:waveburst is a coherent, untriggered burst search method which performs a wavelet transform on blocks of detector data to first produce a time-frequency representation. The wavelet layers are then whitened with a linear prediction error filter, and time-delayed. Correlations and excess-power regions in the  time-frequency plane are then clustered to identify coherent triggers, which are then selected by thresholding based on the abbr:fap.

\begin{figure}
\begin{tikzpicture}[]

%\draw[help lines,step=5mm,gray!20] (0,0) grid (4,3);

\begin{scope}

\fill [red!40] (-2,0.8) rectangle (10,-0.6);
\fill [green!40] (-2,-0.6) rectangle (10,-3.2);
\fill [blue!40] (-2,-3.2) rectangle (10,-5.2);

\fill [yellow!40] (-2,-5.2) rectangle (10,-8.2);

\fill [orange!40] (-2,-8.2) rectangle (10, -13);

\node (signal) {$h$};
 
\begin{scope}[below of = signal, anchor = north, xshift=-2 cm]
 \foreach \x in {1,..., 3} {
 	\node (convolution\x) at (\x, 0) { $\otimes$};
	\draw (signal.south) -- (convolution\x.north);
	\node  at (\x-0.3, 0) {$F_{\x}$};

	\node (xi\x) at (\x, -1) {$\xi_{\x}$};
	\draw(convolution\x.south) -- (xi\x.north);

	\node (addition\x) at (\x,-2.3) { $\oplus$};
	\draw (xi\x.south) -- (addition\x.north);
	\node at (\x-0.3, -2.3) {$N_{\x}$};

	\node (s\x) at (\x, -3.6) {$s_{\x}$};
	\draw (addition\x.south) -- (s\x.north);

	\node [circle, fill] (segment\x) at (\x, -4.5) {};
	\draw (s\x.south) -- (segment\x.north);

	\node [circle, fill] (whiten\x) at (\x, -5.5) {};
	\draw (segment\x.south) -- (whiten\x.north);

	\node [circle, fill] (delay\x) at (\x, -6.5) {};
	\draw (whiten\x.south) -- (delay\x.north);

	\node [circle, fill] (tf\x) at (\x, -8) {};
	\draw (delay\x.south) -- (tf\x.north);

	\node [circle, fill] (excess\x) at (\x, -9.5) {};
	\draw (tf\x.south) -- (excess\x.north);
	
	\node [rectangle, fill] (significance\x) at (\x, -11) {};

	\draw [bend left] (excess\x.south) -- (significance\x.north);

	\node [circle, fill] (triggers\x) at (\x, -12.5)  {};
	\draw (significance\x.south) -- (triggers\x.north);

}

\node (collection) [rectangle, fill, minimum width=2cm] at (2, -14) {};
	
\draw (triggers1.south) -- (collection.north);
\draw (triggers2.south) -- (collection.north);
\draw (triggers3.south) -- (collection.north);
	

\end{scope}
\end{scope}

\begin{scope}[xshift=6cm, every node/.style={text width=7cm}]

\node (signal-text) at (0,0) {A signal, $h$ is generated by an astrophysical source.};
\node (convolution-text) at (0, -2cm) {The signal is convolved with each detector's antenna pattern, $F$. \\ This gives the \emph{antenna response}, $\xi$.};

\node (addition-text) at (0, -4) {The signal, combined with noise, $N$, from the detector, giving the \emph{observed signal}, $s$.};

\node (segment-text) at (0,-5.7) {The recorded signals are split into segments.};
\node (segment-text) at (0,-6.7) {A filter is applied to whiten the data.};
\node (segment-text) at (0,-7.7) {Each detector signal is time-delayed with respect to a given sky location.};

\node (tf-text) at (0,-9.3) {The data from each detector is converted to a time-frequency representation.};
\node (excess-text) at (0,-10.8) {Pixels with excess power are identified, and clusters of these pixels are identified.};

\node (significance-text) at (0, -12.2) {The significance of the clusters are estimated for events in individual detectors.};

\node (trigger-text) at (0, -13.7) {Lists of triggers are produced, which can be sorted by significance, and thresholded.};

\node (collection-text) at (0, -15.2) {The trigger times from each detector are compared, and coincident events are identified.};

\end{scope}



\end{tikzpicture}

\caption{A typical all-sky coincident burst search pipeline.
\label{fig:sources:burst:coincidentsearch}}
\end{figure}

   + omicron / LALInference burst :: The abbr:olib pipeline cite:2015arXiv151105955L is a coincident all-sky burst search pipeline which relies on the use of contant-$q$ transforms to generate time-frequency representations of detector data, in order to identify regions of excess energy. the significance of single-detector triggers are then determined using Bayesian inference to produce a joint detection significance from the network of detectors.
   + Bayeswave :: In contrast to other burst search pipelines, abbr:bayeswave cite:2015CQGra..32m5012C is designed to determine the significance of pre-determined triggers, and does not generate triggers on its own. It takes a direct approach to distinguishing signal transients (bursts) from noise transients (glitches) by directly modelling glitches with Morlet waveforms, and then performing Bayesian model selection to identify the favoured hypothesis (either a noise, glitch, or signal model).

* Mock data challenges and all-sky searches

  Given the complexity of modern burst search algorithms, and their need to operate in a regime of non-Gaussian, non-stationary noise it is important to be able to demonstrate the efficacy of an individual pipeline.
In addition to this, the nature of the noise in abbr:gw detectors makes estimating the sensitivity of each search method difficult, as the time-evolution of the noise abbr:psd will affect the sensitivity over time.
To address these problems pipelines are tested against known signals which are "injected" into the recorded data from the detector.

This process can be performed in two ways, either as a /hardware injection/, where the test mass of the detector is physically actuated (using either an electrostatic drive, or through photon pressure), or as a /software injection/, where the signal waveform is added to the pre-recorded data.
The former process has the advantage of testing the performance of the pipeline "end-to-end", as the signal will be present in the analysed data at all times. 
Indeed, prior to the detection of gls:gw150914 the use of "blind" injections to test the readiness of search algorithms was a standard practice. 
In contrast software injections can be performed offline, and thus do not run the risk of obfuscating an astrophysical signal.
However, as these are added to the recorded data it is necessary to ensure that a consistent set of signals is analysed by all pipelines to provide consistent sensitivity estimates.

At the beginning of the advanced detector era it became clear that the production of these /mock data challenges/ required new infrastructure, and the /Minke/ project was initiated to handle this.

* Minke

/Minke/ is a software library implemented in the ~python~ programming language which is designed to produce large-scale abpl:mdc for burst waveforms. 
In order to ensure consistency with other abbr:gw analyses, and to make use of as much pre-existing, reviewed code as possible, gls:minke makes use of as much functionality as possible from gls:lalsuite, cite:lalsuite.
While Minke was designed for the primary purpose of abbr:mdc production, it also provides a convenient python wrapper to a number of functions from the \texttt{LALSimulation} cite:lalsuite C library, making it a convenient means to generate abbr:gw signals, for example for machine learning training data.

Burst searches are used to search for both totally unmodelled sources, and poorly modelled sources (see section ref:sec:source:burst for a discussion of the various morphologies of these signals). 
gls:minke supports a large subset of these waveforms; analytical waveforms, such as Gaussians and sine-Gaussians are generated using \texttt{LALSimulation}, while more complicated models can be used (such as abbr:nr derived supernova waveforms) can be used to generate signals if the waveform is available either as precomputed strain values in the $+$- and $\times$-polarisations, or decomposed into a spherical harmonic basis.

The process for producing an abbr:mdc using Minke is broken into a number of stages (which are also depicted in figure ref:fig:sources:minke:frame):

1. The distributions of source parameters are specified; these include the probability distributions from which parameters of individual signals are drawn, and the hyperparameters defining those distributions. For example, the injections may be made uniformly across the sky, or a more specific distribution may be chosen.

2. A specification for the signal set is generated as a table of source parameters, with each row specifying a single signal. This table can be stored in XML format for later use.

3. Each signal can then be generated using \texttt{LALSimulation}. In the case of analytical waveforms the appropriate generating function is evaluated, and in the case of a precomputed signal the waveform data is interpolated appropriately for the desired sample rate, and where appropriate, is reconstructed from a spherical harmonic basis.

4. The generated signal must then be convolved with the antenna pattern for each detector involved in the analysis, for the appropriate sky position and time, and must have the appropriate time delay applied relative to the geocentre.

5. The signals, which are now ready to be injected, can be stored either in a GWF frame file, or as ASCII data. The former is used for software injections, and the latter for hardware injections.

6. The analysis-ready abbr:mdc is constructed by adding the injection signal to the detector data, allowing the sensitivity of the detector to a specific signal morphology to be tested over time, in the presence of real noise and glitches.

\begin{figure}
\begin{tikzpicture}[]

%\draw[help lines,step=5mm,gray!20] (0,0) grid (4,3);

\begin{scope}

\fill [pink!40] (-2,2.8) rectangle (10,-3.5);
%\fill [green!40] (-2,-0.6) rectangle (10,-3.2);
\fill [blue!40] (-2,-3.5) rectangle (10,-5);


\node (parameters) at (0,1.5) {$\vec{p}$};

\node (signal) at (0,0) {$h$};

\draw (parameters) -- (signal);
 
\begin{scope}[below of = signal, anchor = north, xshift=-2 cm]
 \foreach \x in {1,..., 3} {
 	\node (convolution\x) at (\x, 0) { $\otimes$};
	\draw (signal.south) -- (convolution\x.north);
	\node  at (\x-0.3, 0) {$F_{\x}$};

	\node (xi\x) at (\x, -1) {$\xi_{\x}$};
	\draw(convolution\x.south) -- (xi\x.north);

	\node [rectangle, fill]  (frame\x) at (\x,-3) {};
	\draw (xi\x.south) -- (frame\x.north);



}


\end{scope}
\end{scope}

\begin{scope}[xshift=5.5cm, every node/.style={text width=7cm}]

\node (signal-text) at (0,1.5) {A set of waveform parameters is selected from the MDC specification.};
\node (signal-text) at (0,.1) {A mock signal, $h$ is generated from defined source parameters.};
\node (convolution-text) at (0, -2cm) {The signal is time-delayed and convolved with each detector's antenna pattern, $F$. A random jitter is added to the central time and amplitude of the signal to simulate calibration uncertainties. \\ This gives the injection-ready signal.};

\node (addition-text) at (0, -4.2) {The injection ready signals are then stored in a form ready to be added to detector noise.};

\end{scope}



\end{tikzpicture}

\caption{The process of frame production for a abbr:mdc using Minke. For software injections the injection-ready signals are normally stored in GWF frame files, ready to be injected into the signal recorded from the detector. For waveforms to be used for hardware injections the signals are simply written out as ASCII-format text files. \label{fig:sources:minke:frame}}
\end{figure}

** O1 and O2 all-sky searches


