/This chapter is broadly a mixture of introductory material regarding astrophysical sources of gravitational waves, the waveforms which those sources are expected to produce, and the models and simulations which are required to produce them. This should stand as a motivation for the material presented later in this work regarding the production of statistical surrogate models. The final sections of this chapter will focus on the need for and production of mock data challenges, their role in testing detection and analysis pipelines, and the development of a consistent infrastructure to support this task./

The astrophysical sources of gravitational waves can be divided
roughly into three categories cite:2009LRR....12....2S

+ Continuous :: sources are expected to produce radiation
  constantly, or at least over long periods of time. The primary
  source of continuous sources for gls:aLIGO are expected to be
  gravitational wave pulsars, but in detectors which are sensitive at
  lower frequencies, such as the proposed gls:LISA mission, the radiation
  from inspiralling binary systems should also be detectable.
+ Transient :: sources produce a strong \emph{burst} of
  gravitational waves over a period of seconds or less. These are
  sources which are primarily expected in the advanced LIGO passband,
  with compact binary coalesences and supernovae being major targets
  for burst searches in the advanced observing runs, however there are
  prospects for burst sources in the gls:LISA regime, for example from
  hyperbolic encounters between compact objects and stars or other
  compact objects  cite:2012PhRvD..86l4012B,2012PhRvD..86d4017D,2008MPLA...23...99C,2008APh....30..105C,2010MmSAI..81...87D,2005PhRvD..72h4009G,2010PhRvD..82j7501B,2011ApJ...729L..23G.
+ Stochastic :: sources are expected to produce a background of
  gravitational waves, from the black holes at the centres of
  galaxies cite:1980Natur.287..307B,2001astro.ph..8028P,2003ApJ...583..616J,2008MNRAS.390..192S,
  and from the universe's inflationary period cite:1988PhRvD..37.2078A.

* Compact Binary Coalescences

#+NAME:fig:cbc_spectrum
#+CAPTION: The frequency spectrum of a compact binary coalescence, alongside the design sensitivity power spectrum of the advanced LIGO detector.
[[./figures/aligo-cbc.pdf]]

  A pair of orbiting objects can also produce gravitational waves, and   as they do so their orbit loses energy, causing the radius of the orbit to shrink cite:1995PhRvL..74.3515B. 
The objects spiral in towards each other. 
This behaviour has already been observed in the Hulse-Taylor pulsar cite:1975ApJ...195L..51H,2005ASPC..328...25W, a system of two neutron stars---one of which is a pulsar--- which, through precise pulsar timing measurements, have been inferred to be  inspiralling, and producing gravitational waves.

The binary system will continue to lose energy via gravitational radiation until it reaches its /innermost stable circular orbit/, after which the objects will merge, and eventually coalesce. 
These coalescence events are powerful sources of gravitational waves, and the chirp produced by the coalescence may be sufficiently luminous to be detected by current, advanced detectors. 
Attempts to detect signals from such coalescing systems were also made during the initial run of the detectors cite:2012PhRvD..85h2002A.
These would be characterised by the distinct pattern of the pseudo-sinusoidal inspiral waveform, followed by a bright burst of radiation, and then a sinusoidal ``ringdown'' as the post-coalescence remnant vibrates\cite{2009LRR....12....2S}. 
Binary coalescences are thus
  classified as transient, or burst sources.

The potential objects which may be involved in an observable binary
coalescence are black holes and neutron stars: both compact
objects. White dwarf binaries may also be observable, and these
systems are expected to be much more abundant than either neutron star
or black hole binaries, but their emission lies within the passband of
gls:lisa---a planned space-based gravitational wave observatory. These
never reach a last stable orbit, as it lies within their physical
diameter, and so the inspiral component of the waveform is the
principle source of gravitational waves. These are expected to be so
numerous in gls:lisa results cite:2013GWN.....6....4A that entirely new statistical methods will be
needed to process the observations, and to allow observations of other
phenomena to be made in their background.

gls:smbbh are believed to collide and merge as part of the merging processes of galaxies. 
Again these binaries should produce signals within the passband of gls:lisa cite:2012CQGra..29l4016A, 
and should be so spectacuarly strong that they are visible in the gls:lisa
data without the \emph{matched filtering} techniques which are required to extract other signals from the data cite:2009LRR....12....2S. 
The observation of these objects would provide much-needed information about the evolution of galaxies and of super-massive black holes.

Inspiralling compact binaries can act as a cosmological distance measure: 
they have two parameters, their period, and the rate at which that period changes (which is calculated by measuring the gls:chirp-mass of the system) which characterise the system, and the
amplitude of the gravitational waves produced is dependent only on the
chirp mass of the source, and the distance from the observer to the
object. As a result it is possible to determine the distance to an
inspiralling system simply by determining the chirp mass and measuring
the brightness of the event. This would provide an additional means of
measuring cosmic acceleration, and, in the gls:LISA era, this would allow
the measurement of acceleration at high redshift using high-mass
binary black holes.

** Numerical relativity 

The study of compact binary systems using gravitational waves relies on solving the relativistic two-body problem; the classical, Newtonian solutions to this problem are Keplerian orbits, however post-Newtonian gravity requires that a mass with orbital angular momentum loses energy in the form of gravitational waves; as such there are no stable solutions of the (general) relativistic two body problem.

*Should definitely include more details about the actual implementation of NR simulations*

The complexity of gls:nr simulations has lead to their adoption of parallelisation technology for multiprocessing and message-passing between processes, however these simulations can still require around a month to produce on computing clusters containing thousands of processors. 

*Should include detail about the different codes which are used for GT and SXS*
   
* Continuous wave sources
The discovery of pulsars by Bell and Hewish in 1967 was an unexpected
discovery for radio astronomy---objects which produce beams of
radiation, and rotate rapidly, like a lighthouse. Not long after their
discovery it became apparent that they were a specific form of neutron
star---the tightly-packed remnant of a massive star which has ended its
life as a supernova.

Being highly-dense, and having a rapid rotation (and hence an
acceleration), pulsars are strong candidates for producing gravitational
radiation. Any irregularity in their structure, such as a bulge (or a
mountain) on their surface. These gravitational waves will produce a
weak signal in the detector, but by observing for long periods of time,
it is possible to make very sensitive measurements, thanks to the
periodicity of the signal.

While no observations of gravitational waves from a pulsar have been
made so far, the lack of any detection by the initial LIGO and VIRGO
interferometers has provided a result in its own right. The sensitivity
of these detectors is well understood, and the /sensitive distance/, the
distance to which the detector is capable of making an observation, has
been calculated. This allows us to exclude the Crab pulsar, for example,
from having any asymmetry greater than one part in 10000 in its
shape\cite{2009LRR....12....2S}, corresponding to a maximum surface
irregularity of 30cm\cite{2014ApJ...785..119A}.

* Stochastic backgrounds

While the gravitational wave detections which we expect to make with the
aLIGO and aVIRGO detectors in the next five years all correspond to
radiation from specific sources, in the LISA era we expect to encounter
a new phenomenon: the gravitational wave
background\cite{2009LRR....12....2S}. This is likely to come from a
number of sources. LISA will be sensitive to compact binary systems for
a much longer period of their evolution, and so rather than just
detecting the final few orbits and the coalescense of objects, we will
be able to observe decades or more of their inspiral. Given the large
population of binary objects in the universe, and the ability of LISA to
detect white dwarf binaries, we can expect the existence of a rich
gravitational wave background at low frequencies: so much so that the
data-handling task will be many orders of magnitude more complicated
than that for the advanced era detectors. Super-massive binary black
holes throughout the universe will also contribute to this background.

Currently-favoured theories of cosmology favour the existence of a
period of cosmological inflation, a process which should have produced
very low-frequency gravitational waves. These were the focus of the
ultimately-refuted BICEP2 announcement\cite{2014PhRvL.112x1101B} of the
discovery of gravitational waves.

* Transient sources
** Bursts
*** Burst waveform models
** Parabolic and hyperbolic encounters
*** Encounter waveforms
** Supernovae

*** Core-collapse supernovae

#+CAPTION: Core-collapse supernova spectrum.
#+NAME:fig:ccsn-spectrum
[[./figures/source-ccsn.pdf]]

 Core collapse supernova (CCSNe) are driven by the release of
 gravitational energy as a massive star's core collapses. Progenitor
 stars of CCSNe have zero-age-main-sequence (ZAMS) masses in the range
 $8\,\msolar \leq M \leq 130\,\msolar$. Much of this energy is stored as
 heat in the protoneutron star remnant, around 99% of the released energy
 is carried-off by neutrinos, around 1% provides the kinetic energy of
 the explosion, while less than $0.01\%$ of the energy is extracted as
 electromagnetic and gravitational radiation \cite{2009CQGra..26f3001O}.

 When the iron core of a star exceeds the Chandrasekhar mass it becomes
 unstable, and undegoes gravitational collapse, and is compressed until
 the neutron degeneracy pressure is able to halt arrest the collapse. At
 this point the core becomes stiff, and the inner core rebounds---a phase
 of the supernova known as "core bounce". The stiff, ultra-dense remnant
 of the collapse is a proto-neutronstar (PNS).

 Gravitational waves are expected to be emitted in a number of periods
 during the collapse, for example during a rotating collapse, and the
 core-bounce which follows it; pulsations of the PNS
 \cite{1966ApJ...145..514M}; and anisotropic neutrino emission
 \cite{1979ApJ...231Q.644E,1978ApJ...223.1037E,1978Natur.274..565T}.

 In order to predict the gravitational waveforms which would be produced
 by a CCSN detailed numerical modelling must be completed, with the most
 modern results from Scheidegger, modelling rotating, axisymmetric
 collapses in three dimensions, and Dimmelmeier\cite{2008PhRvD..78f4056D}
 in two dimensions; and Müller and Ott\cite{2013ApJ...768..115O},
 modelling neutrino-driven supernovae in three dimensions.

 It is possible that core-collapse supernovae could have been detected
 with the initial LIGO detector\cite{2009LRR....12....2S}, although none
 were. At design sensitivity the three-detector network of Advanced LIGO
 and Advanced VIRGO should be able to detect CCSNe to a distance of
 around $\SI{5.5}{\kilo pc}$, in the case of neutrino-driven explosions,
 while rapidly-rotating core-collapses will be detectable to
 $\SI{50}{\kilo pc}$, the distance to the Large Magellanic Cloud. Extreme
 emission scenarios may be detectable as far as $\SI{0.77}{\mega pc}$,
 the distance to M31\cite{2016PhRvD..93d2002G}.

*** Type Ia supernovae

#+NAME:fig:T1a-spectrum
#+CAPTION: Type-1A supernova spectrum.
[[./figures/source-t1asn.pdf]]

 Type Ia supernovae (SNe Ia) are believed to be the result of
 white-dwarfs in binary systems accreting enough matter to exceed the
 Chandrasekhar-mass, and undergoing catastrophic
 core-collapse\cite{2013MNRAS.429.1156S}, however the evolution of the
 binary systems which are the progenitors of Type Ia supernovae is poorly
 understood. Recent work\cite{2015PhRvD..92l4013S} implies that the
 gravitational wave emission from a Type Ia supernova would produce
 decihertz gravitational-waves, peaking at a frequency around . This
 would position SNe Ia as a target for the proposed DECIGO and BBO
 space-based observatories.
*** Supernova waveform models    

** Cosmic string cusps
** Accretion disk instability
* Mock data challenges
