#+TITLE: Exotic compact objects


* Echoes
** TO READ A recipe for echoes from exotic compact objects
  :PROPERTIES:
  :TITLE:    A recipe for echoes from exotic compact objects
  :BTYPE:    article
  :CUSTOM_ID: 2017arXiv170606155M
  :AUTHOR:   {Mark}, Z. and {Zimmerman}, A. and {Du}, S.~M. and {Chen}, Y.
  :JOURNAL:  ArXiv e-prints
  :ARCHIVEPREFIX: arXiv
  :EPRINT:   1706.06155
  :PRIMARYCLASS: gr-qc
  :KEYWORDS: General Relativity and Quantum Cosmology
  :YEAR:     2017
  :MONTH:    jun
  :ADSURL:   http://adsabs.harvard.edu/abs/2017arXiv170606155M
  :ADSNOTE:  Provided by the SAO/NASA Astrophysics Data System
  :END:
  [[file:../papers/1706.06155.pdf][PDF]]
*** Abstract
    Gravitational wave astronomy provides an unprecedented opportunity
    to test the nature of black holes and search for exotic, compact
    alternatives. Recent studies have shown that exotic compact
    objects (ECOs) can ring down in a manner similar to black holes,
    but can also produce a sequence of distinct pulses resembling the
    initial ringdown. These "echoes" would provide definite evidence
    for the existence of ECOs. In this work we study the generation of
    these echoes in a generic, parametrized model for the ECO, using
    Green's functions. We show how to reprocess radiation in the
    near-horizon region of a Schwarzschild black hole into the
    asymptotic radiation from the corresponding source in an ECO
    spacetime. Our methods allow us to understand the connection
    between distinct echoes and ringing at the resonant frequencies of
    the compact object. We find that the quasinormal mode ringing in
    the black hole spacetime plays a central role in determining the
    shape of the first few echoes. We use this observation to develop
    a simple template for echo waveforms. This template preforms well
    over a variety of ECO parameters, and with improvements may prove
    useful in the analysis of gravitational waves.

** TO READ Gravitational wave searches for ultralight bosons with LIGO and LISA
   :PROPERTIES:
   :TITLE:    Gravitational wave searches for ultralight bosons with LIGO and LISA
   :BTYPE:    article
   :CUSTOM_ID: 2017arXiv170606311B
   :AUTHOR:   {Brito}, R. and {Ghosh}, S. and {Barausse}, E. and {Berti}, E. and {Cardoso}, V. and {Dvorkin}, I. and {Klein}, A. and {Pani}, P.
   :JOURNAL:  ArXiv e-prints
   :ARCHIVEPREFIX: arXiv
   :EPRINT:   1706.06311
   :PRIMARYCLASS: gr-qc
   :KEYWORDS: General Relativity and Quantum Cosmology, Astrophysics - High Energy Astrophysical Phenomena, High Energy Physics - Phenomenology, High Energy Physics - Theory
   :YEAR:     2017
   :MONTH:    jun
   :ADSURL:   http://adsabs.harvard.edu/abs/2017arXiv170606311B
   :ADSNOTE:  Provided by the SAO/NASA Astrophysics Data System
   :END:
   [[file:../papers/1706.06311.pdf][PDF]]
*** Abstract
    Ultralight bosons can induce superradiant instabilities in
    spinning black holes, tapping their rotational energy to trigger
    the growth of a bosonic condensate. Possible observational
    imprints of these boson clouds include (i) direct detection of the
    nearly monochromatic (resolvable or stochastic) gravitational
    waves emitted by the condensate, and (ii) statistically
    significant evidence for the formation of "holes" at large spins
    in the spin versus mass plane (sometimes also referred to as
    "Regge plane") of astrophysical black holes. In this work, we
    focus on the prospects of LISA and LIGO detecting or constraining
    scalars with mass in the range $m_s\in [10^{-19},\,10^{-15}]$ eV
    and $m_s\in [10^{-14},\,10^{-11}]$ eV, respectively. Using
    astrophysical models of black-hole populations and black-hole
    perturbation theory calculations of the gravitational emission, we
    find that LIGO could observe a stochastic background of
    gravitational radiation in the range $m_s\in [2\times 10^{-13},
    10^{-12}]$ eV, and up to $\sim 10^4$ resolvable events in a
    $4$-year search if $m_s\sim 3\times 10^{-13}\,{\rm eV}$. LISA
    could observe a stochastic background for boson masses in the
    range $m_s\in [5\times 10^{-19}, 5\times 10^{-16}]$, and up to
    $\sim 10^3$ resolvable events in a $4$-year search if $m_s\sim
    10^{-17}\,{\rm eV}$. LISA could further measure spins for
    black-hole binaries with component masses in the range $[10^3,
    10^7]~M_\odot$, which is not probed by traditional
    spin-measurement techniques. A statistical analysis of the spin
    distribution of these binaries could either rule out scalar fields
    in the mass range $[4 \times 10^{-18}, 10^{-14}]$ eV, or measure
    $m_s$ with ten percent accuracy if light scalars in the mass range
    $[10^{-17}, 10^{-13}]$ eV exist.
