The production of high-accuracy waveforms is possible thanks to advances in the field of abbr:nr, in which the full set of Einstein equations can be solved numerically (see section ref:sec:sources:cbc:nr for a more detailed discussion of the development of abbr:nr). 
This can be done reliably for the low-mass compact binary systems of interest to the current generation of ground-based gravitational wave observatories, however these simulations are computationally expensive, and can require thousands of CPU hours to run in situations where the mass ratios and spins of the black holes are small. 
A simulation of a full 350-cycle gravitational waveform spanning the entire advanced LIGO band has been produced cite:2015arXiv150204953S, however this required several months of high-performance computing to complete cite:2016CQGra..33l5025D, despite employing numerous techniques to reduce wall-clock computation time. 
As a result fewer than 1000 waveforms are available, many of these much shorter than 350 cycles long. 
Abbr:bbh coalescences are described by a number of physical parameters: the ratio of the two component black holes' masses, $q$; the vector of each component's spin, ${\vec{s}}_1 = (s_{1x}, s_{1y}, s_{1z})$ and ${\vec{s}}_2 = (s_{2x}, s_{2y}, s_{2z})$, defined such that the $z$-component of each vector is parallel to the total angular momentum vector, $\vec{L}$, for the system (i.e. $\hat{s}_{1z} = \hat{s}_{2z} = \hat{L}$, see figure ref:fig:heron:bbhcartoon for the arrangement of these vectors); and the time, $t$, relative to a fixed reference time, for example the time of coalescence of the binary.




As noted in section ref:sec:sources:cbc:approximants, a number of /analytical approximant/ waveforms have been produced in recent years in order to provide approximate waveforms much more quickly than abbr:nr is capable of.
These models, while capable of producing waveforms over a wide range of the abbr:bbh parameter space, are calibrated against only a small number of waveforms, resulting in waveforms produced in much of the parameter space having an unknown accuracy.

\begin{figure}[b]
\begin{center}
\begin{tikzpicture} 

\begin{scope}[xshift=-3cm]
\draw [shorten >=0.15cm, thick, ->] (0,0,0) -- (0,0,1) node {$\hat{y}$};
\draw [shorten >=0.25cm, thick, ->] (0,0,0) -- (1,0,0) node {$\hat{x}$};
\draw [shorten >=0.25cm, thick, ->] (0,0,0) -- (0,1,0) node {$\hat{z}$};
\end{scope}

\fill (1,1,1) circle (0.5);
\draw [shorten >=0.25cm, ultra thick, ->] (0.5,0.5,1) -- (2,2,1) node {$\vec{s}_1$};
\fill (-1,1,1) circle (0.25);
\draw [shorten >=0.2cm, ultra thick, ->] (-0.75, 0.75,1) -- (-1.5,1.5,1) node {$\vec{s}_2$};

\draw [dotted] (-0.25,.5,0) ellipse (1. and 0.25);

\draw [shorten >=0.25cm, ultra thick, ->] (-0.25,0.5,0) -- (-0.25,1.5,0) node {$\vec{L}$};
\end{tikzpicture}
\end{center}
\caption[A cartoon of a binary black hole system]{A cartoon depicting the geometrical arrangement of the two black holes in a coalescing binary system, and the various vector quantities involved. Here $\vec{s}_{1}$ and $\vec{s}_{2}$ are the spin vectors of the individual component black holes during the inspiral, and $\vec{L}$ is the total angular momentum vector for the system. The spin vectors are defined such that $\hat{s}_{z}$ for each is equal to $\hat{L}$, and the other two components are orthogonal. \label{fig:heron:bbhcartoon}
}

\end{figure}

* Numerical Relativity Waveform data
  :PROPERTIES:
  :CUSTOM_ID: sec:heron:nr-data
  :END:
  \label{sec:heron:nrdata}

abbr:nr simulations for abbr:cbc events simulate the behaviour of the gls:riemann-tensor over a finite period of time prior to, during, and immediately following the merger of the two objects.
This simulation allows the extraction of a gravitational waveform at a large distance from the merger event, where the flat metric approximation of equation ref:eq:linearised-metric is valid.
Observations of the strain are made, and time-stamped. 
These data then constitute the waveform data, which are normally stored in a spherical harmonic decomposition in an ~HDF5~ format cite:2017arXiv170301076S.
Thanks to the non-uniform time sampling which abbr:nr codes employ, the data from the simulation will normally need to be interpolated (in time) and resampled to be of use for data analysis, or as training data for a surrogate model.
In the models presented in this chapter this interpolation was performed by the ~pycbc~ library cite:2016CQGra..33u5004U,alex_nitz_2019_3265452,2014PhRvD..90h2004D.

The waveform data used in this chapter is derived from the Georgia Tech Catalogue cite:2016CQGra..33t4001J, with the waveforms evaluated in the time domain, and then aligned such that the time location in the timeseries corresponding to the maximum value of abbr:hrss was labelled $0$.
A timeseries is generated for each abbr:gw polarisation, giving two timeseries, for $h_{+}(t)$ and $h_{\times}(t)$ for each abbr:nr waveform.

Each waveform is parameterised by seven quantities (the mass ratio and the spin vectors of each component black hole) in a vector which is denoted ${\boldsymbol{x}_i}$. 
Each strain value, $h_i$, within the waveform is further parameterised by a time relative to the maximum strain value in the waveform, and thus each training point is parameterised by an 8-dimensional parameter vector, denoted ${\boldsymbol{x}_i}'$.
This provides a training set which has 8 input dimensions, and a single output dimension, with the form 
\begin{equation}
{\mathcal{D}} = \left\{ ({\boldsymbol{x}'_i},  h_i) | i = 1, 2, \dots, N \right\}
\end{equation}
for $N$ the total number of strain samples used from all of the training waveforms, and $h_i = h(t_i, \vec{x}_i) = h(\vec{x}'_i)$ is the strain value of a waveform at time $t_i$ relative to the maximum strain value of the waveform, and at a location $\vec{x}$ in parameter space. 
The distribution of training waveforms throughout the parameter space is shown in figure ref:fig:sources:cbc:nr:gtcoverage, on page \pageref{fig:sources:cbc:nr:gtcoverage}.





* Gaussian process regression for waveforms
  \label{sec:heron:waveformgpr}

Current waveform models lack a natural means to account reliably for uncertainty in the waveforms which they generate.
A side-effect of this is important in parameter estimation of these signals, as systematic uncertainties in the waveform model will result in the introduction of a bias to the parameter estimation process.


To illustrate how such a model can be constructed, in this section I will detail the construction of two abbr:gp models which use waveforms generated from the \texttt{IMRPhenomPv2} waveform model as their training data.
In the first model I will use only non-spinning waveforms, varying only in their mass-ratio.
In the second I will introduce characteristic spin to the model, to create a three-dimensional abbr:gp regression model.

Later in this chapter I will detail the results presented in cite:2019arXiv190309204W of a abbr:gp model for precessing waveforms which has been trained using data from abbr:nr simulations.

** A simple non-spinning model

For the first demonstration model I will use 15 waveforms produced using the ~IMRPhenomPv2~ waveform model with mass-ratios spaced uniformly in log-space between $q=0.1$ and $q=1.0$.
Each waveform is composed only from the $(2,2)$ spherical harmonic mode, and the strain is labelled as $h_{2,2}$.
Each waveform was sampled at $\SI{4096}{\hertz}$ for a total system mass of $\SI{60}{\solMass}$. 
The strain data is generated assuming that the source is placed at a distance of $\SI{1}{\solMass}$ (or approximately $\SI{1.477}{\meter}$ from the observer, allowing the strain to be easily rescaled to any distance, $r$, by dividing the amplitude by the distance to the source (in units of $\solMass$).
The strain data used for training is then denoted $rh_{2,2}$.
The timestamps are then divided by the total mass of the system to produce a waveform which can be rescaled for an arbitrary total mass by multiplying the timestamps by the desired total mass (in units of $\solMass$).
The training data is plotted in figure ref:fig:heron:imr:testdata.

\begin{figure}
\includegraphics{figures/heron/imr-test-training.pdf}
\caption[The \texttt{IMRPhenomPv2} training data for a demonstration model]{The training data used for the non-spinning demonstration abbr:gp surrogate model. Here the amplitude of the data, $rh_{2,2}$ represents the $(2,2)$-mode strain, multiplied by the distance from the source to the observer. The physical strain can be recovered by dividing this quantity by the desired distance from the observer to the source.}
\label{fig:heron:imr:testdata}}
\end{figure}

The covariance structure for this model consists of two abbr:se kernels (one for each dimension, time and the natural logarithm of the mass ratio) and a constant kernel as a scale-factor:
\begin{equation}
\label{eq:heron:imr:covariance}
K = \Con \times \SE^{(t,\log{q})}.
\end{equation}
abbr:se covariance functions were chosen as it allows smooth data generating functions to be modelled well, and there was no reason to assume that the function contained discontinuities, or non-smooth regions.
The constant kernel is included to allow the abbr:gp extra flexibility to determine the variance of the estimate.
A small amount of noise is added to the covariance function (with a mean of $1\ee{-6}$) to improve the numerical stability of the matrix inversion process.
The hyperparameter values for each part of the kernel were determined by maximising the log-likelihood of the abbr:gp to complete the training of the model.

A sample of a waveform generated from this model is plotted in figure ref:fig:heron:imr:test1, with the mean and variance of the abbr:gp plotted as a dashed grey line and shaded grey region respectively.
Individual draws from the predictive posterior distribution are plotted as solid grey lines, depicting how individual fitting functions drawn from the posterior behave, clustering closely about the mean, with the behaviour in the ringdown portion of the waveform showing the greatest variance, which is reflected in the greater width of the variance region in this part of the waveform.

\begin{figure}
\includegraphics{figures/heron/imr-test-q0d8.pdf}
\caption[Draws from a GPR model trained on \texttt{IMRPhenomPv2} waveform data]{One hundred draws from a abbr:gp trained on waveform data produced from the \texttt{IMRPhenomPv2} analytical waveform model. 
These draws are produced for a non-spinning, non-equal-mass configuration ($\vec{s_1} = (0,0,0)$, $\vec{s_2} = (0,0,0)$, $\vec{q} = 0.8$), and each is shown shown as a light grey line.
The output of \texttt{IMRPhenomPv2} is overlaid in red. 
The mean draw from the abbr:gp is shown as a grey dashed line, while the associated variance is plotted as a grey-filled region surrounding the mean. 
\label{fig:heron:imr:test1}}
\end{figure}

As this is a two-dimensional model, it is possible to inspect the entire surface of the mean function produced by the surrogate model; this, along with the variance of the model prediction is plotted in figure ref:fig:heron:imr:testplane.

\begin{figure}
\includegraphics{figures/heron/imr-test-plane.pdf}
\caption[Two dimensional surface plot of the non-spinning \texttt{IMRPhenomPv2}-trained GPR surrogate]{The mean (left panel) and variance (right panel) of the abbr:gp surrogate model trained on \texttt{IMRPhenomPv2} over the $(t,q)$-plane.
\label{fig:heron:imr:testplane}}
\end{figure}

In order to compare the output of the abbr:gp surrogate model to ~IMRPhenomPv2~ I calculate the match of the waveform generated by each model.
The match is defined between two waveforms as 
\begin{equation}
\label{eq:heron:testing:match}
  \mathcal{M}(h_{\text{model}}, h_{\text{ana}}) = \max_{t_0, \phi_0} \frac{ \langle h_{\text{model}}, h_{\text{ana}} \rangle}
  {\sqrt{ \langle h_{\text{model}}, h_{\text{model}} \rangle \langle h_{\text{ana}}, h_{\text{ana}} \rangle}}.
\end{equation}
where $h_{\text{model}}$ and $h_{\text{ana}}$ are respectively the timeseries predicted by the model and the analytical approximant, $t_0$ and $\phi_0$ are the merger time and merger phase, and $\langle \cdot, \cdot \rangle$ is the noise-weighted inner product between two waveforms.
This is defined as 
\begin{equation}
\label{eq:noiseweightedinner}
  \langle a, b \rangle = \Re \int_{- \infty}^{\infty} \frac{ \tilde{a}^*(f) \tilde{b}(f) }{ S_n (f) } {\text{d}f}
\end{equation}
for $\tilde{a}$ and $\tilde{b}$ respectively the Fourier transforms of the timeseries $a$ and $b$, $S_n$ the amplitude spectral density of the noise, and $f$ the frequency.
It will also be convenient at this point to define the /mismatch/ as $1-\mathcal{M}$.

The match is a useful quantity to consider, as it is widely used in abbr:gw signal analysis, thanks to its use in matched filtering, which is the optimal filter for maximising abbr:snr when additive noise is present in data cite:strain.conventions.

I calculate the (noise-free, with $S_n(f) = 1$) match between the mean waveform from the abbr:gp surrogate and the waveform from ~IMRPhenomPv2~  for 100 mass ratios between $q=0.1$ and $q=1.0$ in figure ref:fig:heron:imr:match.
The match of the model is consistently above $0.995$ at each mass-ratio tested (although there is a notable drop in match around $0.35$ corresponding to one of the locations furthest from training data).
While the use of match demonstrates that the abbr:gp is capable of reproducing the structure of a waveform accurately it will fail to characterise problems with a model which incorrectly predicts the amplitude of the waveform. 
The match (and mismatch) are the standard metric which is used for evaluating waveform models, however there may be need for additional checks (beyond simply verification by-eye as in plot ref:fig:imr:test1).

\begin{figure}
\includegraphics{figures/heron/imr-test-match.pdf}
\caption[Matches between the \texttt{IMRPhenomPv2} derived waveforms and those from the GPR model]{The match between the waveforms produced by the \texttt{IMRPhenomPv2} and abbr:gp models across one hundred different mass ratios. The mean waveform from the abbr:gp model was used for this plot.
\label{fig:heron:imr:match}}
\end{figure}

** A model with effective spin

In order to extend the model from two dimensions (time and mass ratio), in this section I will introduce a model which additionally models systems with spin.
For simplicity this spin is limited to parallel-spinning systems in which each component black hole has the same spin. 
Additionally, for this demonstration, all of the waveforms used in training were from systems where the spin of the component black holes was parallel to the total angular momentum of the system.

As with the non-spinning model in the previous section, the covariance structure for this model consists of squared exponential kernels, with two additional dimensions added for the $z$-component of each black hole's spin:
\begin{equation}
\label{eq:heron:spin:covariance}
K = \Con \times \SE^{(t,\log{q},s_{1z},s_{2z})}.
\end{equation}
As with the non-spinning model in the previous section the abbr:se kernel is used to model each data-space dimension as these are expected to vary smoothly.


\begin{figure}
\includegraphics{figures/heron/spin-test-training.pdf}
\caption[Training waveforms with spin from \texttt{IMRPhenomPv2} used for the GPR model]{
The training data for the spinning abbr:gp surrogate model, derived from the \texttt{IMRPhenomPv2} approximant model.
Four different values of spin were used to produce this data, $s_{1z} = s_{2z} = \{0, 0.33, 0.66, 0.99\}$.
\label{fig:heron:spin:training}}
\end{figure}

Again the model is trained with a Newtonian optimiser, and tested against the direct output of the \texttt{IMRPhenomPv2} model, by calculating the noise-free match over the parameter space. 
The results of this comparison are displayed as the surface plot in figure ref:fig:heron:spin:matches.
In the majority of the parameter space the mismatch is very small (less than $0.05$), however the abbr:gp model struggles to replicate the behaviour of \texttt{IMRPhenomPv2} at high-spins (where the waveform evolves rapidly due to the extreme physics involved), and at low mass-ratios (corresponding to asymmetric systems) where again the behaviour of the waveform is more complicated thanks to the underlying physics of the orbit.
Three bands of high mismatch can be seen at locations approximately half-way between the locations of waveform samples in the spin dimension, implying that more than four samples are required for a better model.

\begin{figure}
\includegraphics{figures/heron/spin-test-ms-plane.pdf}
\caption[Matches between \texttt{IMRPhenomPv2}-derived waveforms and those from a GPR model which includes spin effects]{Matches across the mass-ratio and $s_{1z} = s_{2z}$ plane between the GPR model and waveforms generated directly from \texttt{IMRPhenomPv2}.


\label{fig:heron:spin:matches}}
\end{figure}

Using an analytical approximant model such as ~IMRhenomPv2~, which was used here, or ~SEOBNRv3~, grants the ability to generate training data on demand and at whim; this is a situation which is not possible when using abbr:nr waveforms. 
In the following sections I will discuss the development of a model trained entirely off these waveforms, and the challenges which this approach posed. 


* Heron: A model using numerical relativity waveforms
  \label{sec:heron:trainingdata}

The Heron model was created by training a abbr:gp regression model on data from the Georgia Tech abbr:bbh waveform catalogue cite:2016CQGra..33t4001J.
It is designed as a proof-of-concept surrogate model which operates over the eight dimensions of the abbr:bbh parameter space, demonstrating both that abbr:gp regression is a useful technique for dealing with this high-dimensional problem, but also that training can be carried-out directly from abbr:nr data.

The model is constructed using the $(2,\pm 2)$-modes of the $+$-polarisation of the strain data from these waveforms, which are produced using ~pycbc~, as described in section ref:sec:heron:nrdata.
The training data is produced in a similar fashion to the training data for the previous examples, substituting the ~IMRPhenomP2~ model for abbr:nr data.
The abbr:nr waveforms are sampled at $\SI{1024}{\hertz}$ and nominally evaluated at a total system mass of $\SI{60}{\solMass}$. 
The strain values are then multiplied by a factor of $\SI{e19}{}$, and the time values by $\SI{100}{}$, which were found to substantially reduce the time required to run the optimisation and matrix inversion steps during the training and evaluation of the model respectively. The values of the various spin components already lie within a range $[-1,1]$, and so these were left unchanged.
As in the previous examples the model was trained on the natural log of the mass ratio, which was again found to produce a better surrogate model.

The outputs of the model must be suitably rescaled to provide waveforms corresponding to the correct total system mass, and in physical units.

The outputs of the model which are presented in this chapter assume that the source is observed "face-on", and therefore there is no variation in the angle at which the source is observed.

The covariance structure of the Heron model follows the structure of the previous examples, but adds an extra four dimensions to account for the additional spin parameters in the abbr:nr data, giving a covariance function

\begin{equation}
\label{eq:heron:heron:covariance}
K = \Con \times \SE^{(t, \log q, s_{1x}, s_{1y}, s_{1z}, s_{2x}, s_{2y}, s_{2z})}
\end{equation}

# ** Computational Complexity

# A major drawback of the use of abpl:gp is the need to invert the covariance matrix in order to produce predictions. 
# Matrix inversion is a computationally intensive task which scales in memory with $N^2$, for $N$ training points, and with $N^3$ in time. 
# The standard approach to GPR described in equation ref:eq:predictive-gp thus rapidly becomes impractical, requiring large quantities of memory for even moderately sized training sets. 
# In order to overcome these scaling problems, approximate simplify the inversion of the covariance matrix by making simplifying assumptions about its form. 
# One example is the use of the approximate HODLR cite:hodlr inversion method, which allows inversion to be carried out in $\mathcal{O}(N \log^2 N)$ operations. 
# This approach is possible because kernels such as the exponential squared kernel produce covariance matrices which can be arranged to form Hierarchical off-diagonal low rank (HODLR) matrices. 
# The off-diagonal blocks are then factorised using partial-pivoted LU decomposition, and the on-diagonal blocks are factorised using a more accurate algorithm, such as Cholesky decomposition. 
# The block inverses are then recombined to provide the (approximate) overall matrix inverse.

# In producing our surrogate model we employed the HODLR method for calculating the matrix inverse, using the implementation in the =George= cite:hodlr Python package.


* Verification of the model
  \label{sec:heron:verification}

The sparisty of training data poses a considerable challenge to the testing and verification of a model such as the Heron model; conventional approaches to testing such a model involve setting aside a fraction of the training data to compare to the model output when evaluated at the parameter space location of each test datum. 

The quantity of numerical relativity waveforms available at present in the Georgia Tech catalogue makes this approach difficult, as some regions of the parameter space are very sparsely sampled, and omitting a training waveform in this location may significantly complicate the process of training the model.
To overcome this I have carried out four separate categories of test on the Heron model.

+ In-sample tests :: where the entire catalogue of available training waveforms are used to condition the abbr:gp used by the model. Waveforms are then produced from the model at the parameter locations which correspond to each of the training waveforms, and the match between the Heron waveform and the abbr:nr waveform is calculated.

+ Out-of-sample tests :: where a single waveform from the catalogue is omitted from the set of training waveforms used to condition the abbr:gp, but the hyperparameters which were determined during training of the full model are used. A abbr:gp model is conditioned on a reduced catalogue for each waveform, and the waveform is produced from the reduced Heron model which corresponds to the omitted abbr:nr waveform. The match is then computed between these two waveforms.

+ Tests against phenomenological models :: where the match is computed between waveforms produced by Heron and by other waveform models, such as \texttt{SEOBNRv3} and \texttt{IMRPhenomPv2}.

+ Tests against other abbr:nr catalogues :: where the match is computed between waveforms from another abbr:nr catalogue and a waveform corresponding to the same parameters produced by the Heron model.

Each approach to testing has different advantages and disadvantages, and test for different aspects of the model's performance.

** In-sample tests of the Heron model
   \label{sec:heron:testing:in}

   The simplest set of tests which I perform on the Heron model are /in-sample/ tests, which effectively test the model's ability to reproduce its own training data. 
For the Heron model this involved computing the mean waveform from the abbr:gp corresponding to each waveform which was used in the training set.
The match was then calculated between each mean waveform and the corresponding abbr:nr training waveform using the expression for waveform match, $\mathcal{M}$, given in equation ref:eq:heron:testing:match.

In-sample testing ought to reveal problems with the choice of hyperparameters in the model, or inconsistencies in the training data itself. 
Figure  ref:fig:heron:testing:in:hist plots the histogram of the mismatch (equal to $1-\mathcal{M}$) values which resulted from these tests against the Georgia Tech waveforms used as the training data (plotted as the black-outlined histogram).
Reassuringly the mismatch between the vast majority of the model outputs and the training data are small; a small number of outliers appear to have a mismatch greater than $0.01$.
Figure ref:fig:heron:testing:in:distance plots the Euclidean distance between each sampled point and the next-nearest training datum (calculated as the norm of the vector between the two points) and the mismatch.
This reveals that a small number of points which are very close to other points in the training data are generally responsible for these high mismatches.
This may indicate that the model is struggling to fit a smooth function to a small number of closely-spaced waveforms.
Further work is likely to be needed to identify whether these outliers are the result of flawed training data, or a some other problem with the model.

The distribution of mismatches between the Heron model and the abbr:nr data shows that for the majority of waveforms in the test the mismatch is smaller than between the abbr:nr data and either of the approximant models.
This is reassuring, however, since the approximant models are conditioned on abbr:nr data, and are not necessarily conditioned on waveforms at the same locations as the test waveforms (whereas the Heron model /is/ for this in-sample test), this does not provide a comprehensive measure of the Heron model's effectiveness as a surrogate.

\begin{figure}
\includegraphics{figures/heron/in-sample-hist.pdf}
\caption[Mismatches between Heron, Georgia Tech waveforms, and analytical approximants from in-sample testing]{The distributions of mismatches between mean waveforms from the Heron model and each of the \gls{nr} waveforms from the Georgia Tech waveform catalogue (black outline histogram) used in the training set using the procedure described in section \ref{sec:heron:testing:in}.
Additionally, the mismatch distributions between waveforms produced at the same parameters as the \gls{nr} waveforms by the \texttt{SEOBNRv3} (red outline histogram), and the \texttt{IMRPhenomPv2} (blue outline histogram) phenomenological waveform models are plotted. 
For comparison the distributions of mismatch between the same Georgia Tech waveforms and the corresponding waveforms from the \texttt{SEOBNRv3} and \texttt{IMRPhenomPv2} models are plotted as solid red and blue histograms respectively.
 \label{fig:heron:testing:in:hist}}
\end{figure}


\begin{figure}
\includegraphics{figures/heron/distance-v-mismatch-insample.pdf}
\caption[Mismatches of the Heron model compared to the distance to near-by training points]{The mismatch between mean waveforms produced by the Heron model and \gls{nr} waveforms compared to the distance to the next-nearest training waveform in the training data.
Here the distance is calculated simply as the Euclidean distance between the two points in parameter space.
 \label{fig:heron:testing:in:distance}}
\end{figure}


** Out-of-sample tests of the Heron model
   \label{sec:heron:testing:out}

A more rigorous test of a predictive model involves comparing the model's output in a region of the parameter space which does not contain a training datum. This process, known as out-of-sample testing, is difficult for the Heron model, thanks to the large (seven dimensional) parameter space, and the small number of available training waveforms (132).
As a result, removing a substantial fraction of the waveforms in order to produce a set of test data would be likely to substantially affect the predictive power of the model.

To overcome this I have performed a /leave-one-out/ testing procedure.
In order to do this multiple training datasets are produced; from each a single waveform is omitted.
This reduced dataset is then substituted for the data on which the full Heron model's abbr:gp is conditioned, retaining the same hyperparameter values as the full model.
The reduced Heron model is then evaluated at the parameter location corresponding to the omitted waveform, in order to compute a predicted mean waveform. 
The mismatch between the predicted waveform and the omitted abbr:nr waveform was then computed, and the distribution of these mismatches is plotted in figure ref:fig:heron:testing:out:hist as a black-outlined histogram.

In contrast to the in-sample tests from section ref:sec:heron:testing:in the out-of-sample tests do give some indication of the model's capability as a surrogate model. 
The mismatches between the leave-one-out model and abbr:nr data in ref:fig:heron:testing:out:hist show that the Heron model is capable of producing waveforms which have a small mismatch with the abbr:nr waveforms, with the vast majority having a mismatch smaller than $0.1$.
The maximum abbr:snr, \rho_{\text{eff}}, at which the true waveform and the model waveform cannot be distinguished by a parameter estimation process is a function of the mismatch ($1 - \mathcal{M}$) (that is, below an abbr:snr of $\rho_{\text{eff}}$ the parameter estimation process is not worsened by the use of the surrogate compared to an abbr:nr waveform), with $\rho_{\text{eff}}$ defined cite:2016PhRvD..93j4050K,2008PhRvD..78l4020L 
\begin{equation}
\label{eq:mismatch-snr}
\rho_{\text{eff}} = \frac{1}{\sqrt{2(1-\mathcal{M})}}.
\end{equation}
Since a mismatch of $0.1$ will be indistinguishable below an abbr:snr of $7$ the model is acceptable for weaker signals which might be expected in advanced gls:ligo.


\begin{figure}
\includegraphics{figures/heron/out-sample-hist.pdf}
\caption[Mismatches between Heron, Georgia Tech waveforms, and analytical approximants from leave-one-out sampling]{The distributions of mismatches between mean waveforms from the Heron model and each of the \gls{nr} waveforms from the Georgia Tech waveform catalogue (black outline histogram) used in the training set using the leave-one-out (LOO) testing procedure detailed in section \ref{sec:heron:testing:out}.
Additionally, the mismatch distributions between waveforms produced at the same parameters as the \gls{nr} waveforms by the \texttt{SEOBNRv3} (red outline histogram), and the \texttt{IMRPhenomPv2} (blue outline histogram) phenomenological waveform models are plotted. 
 \label{fig:heron:testing:out:hist}}
\end{figure}

The variation of mismatch over the parameter space of the Georgia Tech catalogue is explored in figure ref:fig:heron:testing:out:tri, with waveforms with higher mismatch generally being in areas which are separated from the main body of training data.

\begin{figure}
\makebox[\textwidth][c]{\includegraphics[trim={1cm 0 4.5cm 4cm},clip]{figures/heron/gt_match_triangle.pdf}}
\caption[Corner plot of leave-one-out mismatches between Heron and the Georgia Tech catalogue]{A corner plot across the \gls{bbh} parameter space showing the leave-one-out mismatch, as described in section \ref{sec:heron:testing:out}, between the mean waveform produced by each (reduced) Heron model, and the corresponding omitted Georgia Tech \gls{nr} waveform.
 \label{fig:heron:testing:out:tri}}
\end{figure}

** Tests against other models

It may also be helpful to understand how the outputs of the Heron model compare to conventional phenomenological approximants which are in widespread use.
To do this I calculated the mismatch between the output of the Heron model at the same parameter locations as the in-sample and leave-one-out tests.

The results of these tests are plotted in figures ref:fig:heron:testing:in:hist and ref:fig:heron:testing:out:hist for the in-sample and leave-one-out scenarios respectively. 
In addition, figure ref:fig:heron:testing:in:hist shows the distribution of mismatches between the training abbr:nr data and each of these models (as solid histograms).
In the in-sample case the Heron model reproduces the abbr:nr waveforms with substantially lower mismatch than either phenomenological model. 
This behaviour is to be expected, since the Heron model has direct access to the abbr:nr data, where the phenomenological models do not. 
It is worth noting that the mismatch for ~SEOBNRv3~ is consistently smaller than that of \texttt{IMRPhenomPv2} against both abbr:nr and the Heron model. 
~IMRPhenomPv2~ is known to be accurate over a smaller range of black hole spins than the ~SEOBNRv3~ model.
The leave-one-out distributions are more interesting, as the Heron model here produces a distribution of mismatches which is comparable to ~SEOBNRv3~, with tail of smaller mismatches, indicating that the model retains comparable predictive power to the phenomenological model.


** Tests against other catalogues
   \label{sec:heron:testing:sxs}

While removing waveforms from the Georgia Tech catalogue to hold back for testing data may be detrimental to the Heron model, a number of other waveform catalogues are available, including the extensive SXS catalogue cite:2013PhRvL.111x1104M,2018arXiv181207865V,2019PhRvL.122a1101V,2016CQGra..33p5001C,2016PhRvD..94f4035A,2016PhRvD..93h4031B (and described in section ref:sec:sources:cbc:catalogues:sxs).

Ideally an abbr:gp model would include waveforms from both catalogues, in order to account for systematic uncertainties between the two catalogues.
However, given that the Heron model is trained only on the Georgia Tech catalogue it is possible, with care, to compare the output of the Heron model to abbr:nr waveforms in the SXS catalogue.
This comparison must be interpreted with care, however, due to the presence of said systematic uncertainties, and the mismatch between the Heron model and the abbr:nr waveforms will not take this into account.

The matches between 243 waveforms from the SXS catalogue and the corresponding mean waveform from Heron are plotted in figure ref:fig:heron:testing:sxs:tri showing the mismatch across the parameter space.
The distribution of these mismatches is plotted in figure ref:fig:heron:testing:sxs:hist (as a black-outline histogram) with the mismatch distributions of the two phenomenological models at the same parameters plotted for comparison.
Again the Heron model produces a distribution comparable to ~SEOBNRv3~.

\begin{figure}
\makebox[\textwidth][c]{
\includegraphics[trim={1cm 0 4.5cm 4cm},clip]{figures/heron/sxs_match_triangle.pdf}
}
\caption[Corner plot of mismatches between Heron and the SXS catalogue]{A corner plot across the parameter space of the SXS waveform catalogue showing the  mismatch between the mean waveform produced by the Heron model and each SXS \gls{nr} waveform, resulting from the testing procedure detailed in section \ref{sec:heron:testing:sxs}.
 \label{fig:heron:testing:sxs:tri}}
\end{figure}

\begin{figure}
\includegraphics{figures/heron/sxs-sample-hist.pdf}
\caption[Corner plot of leave-one-out mismatches between Heron and the SXS catalogue]{The distributions of mismatches between mean waveforms from the Heron model and each of the \gls{nr} waveforms from the SXS waveform catalogue (black outline histogram) using the testing procedure detailed in section \ref{sec:heron:testing:sxs}.
Additionally, the mismatch distributions between waveforms produced at the same parameters as the \gls{nr} waveforms by the \texttt{SEOBNRv3} (red outline histogram), and the \texttt{IMRPhenomPv2} (blue outline histogram) phenomenological waveform models are plotted. 
 \label{fig:heron:testing:sxs:hist}}
\end{figure}


* Example waveforms
   \label{sec:heron:examples}

While I have discussed at length the various tests which I carried out on the Heron model, it is valuable to be able to visually compare the output of this model with the phenomenological models used in testing.

Figures ref:fig:heron:example:nr, ref:fig:heron:example:nonspin, ref:fig:heron:example:spin, and ref:fig:heron:example:precessing illustrate the output of the model in a variety of scenarios, respectively for a non-spinning , non-equal mass system; for a non-spinning, equal mass system; a system with aligned spins; and a system with non-aligned spins.

In each figure the ~IMRPhenomPv2~ and ~SEOBNRv3~ waveforms are overlaid on draws from the model, alongside its mean prediction, and the variance of the prediction.

I have plotted the distribution of mismatches between the model predictions and the two phenomenological approximants are shown in the right panel of each figure, with matches calculated between the approximant waveforms (plotted as solid lines) and one-hundred sample waveforms drawn from the model (plotted as histograms). 

Figure ref:fig:heron:example:nr shows a waveform produced from the various models at the same parameter location as one of the Georgia Tech abbr:nr waveforms, which is plotted alongside for comparison.

\begin{figure*}
  \includegraphics[width=\textwidth]{figures/heron/withnr.pdf}
  \caption[Predictions from the Heron model, compared to an NR waveform]
{\textbf{abbr:gp regression predictions, compared to abbr:nr}. 
One hundred draws from the Gaussian process (left panel) for a non-spinning configuration ($\vec{s_1} = (0,0,0)$, $\vec{s_2} = (0,0,0)$, $q = 0.625$), shown as light grey lines compared to two analytical approximant models, \texttt{SEOBNRv3} and \texttt{IMRPhenomPv2} in red and blue respectively. 
The mean draw from the Gaussian process is shown as a grey dashed line, while the associated variance is plotted as a grey-filled region surrounding the mean. 
The differences between the phenomenological model and the \gls{gp} regression model waveforms are seen to also exist between the phenomenological model waveforms and the \gls{nr}-derived waveform (\texttt{GT0374}), plotted here in green. 
In the right panel the distribution of mismatches between the samples and both phenomenological waveforms are shown, with the vertical lines representing the mismatch between the \gls{gp} regression and the phenomenological waveform.
    \label{fig:heron:example:nr}
  }
\end{figure*}


\begin{figure*}

  \includegraphics[width=\textwidth]{figures/heron/nonspin-equalmass.pdf}
  \caption[A Heron waveform from a non-spinning system]
{\textbf{Non-spinning waveform}. One hundred draws from the Gaussian process (left panel) for a non-spinning, equal-mass configuration ($\vec{s_1} = (0,0,0)$, $\vec{s_2} = (0,0,0)$, $q = 1.0$), shown as light grey lines compared to two analytical approximant models, \texttt{SEOBNRv3} and \texttt{IMRPhenomPv2} in red and blue respectively. The mean draw from the Gaussian process is shown as a grey dashed line, while the associated variance is plotted as a grey-filled region surrounding the mean. In the right panel the distribution of mismatches between the samples and both phenomenological waveforms are shown, with the vertical lines representing the mismatch between the \gls{gp} regression and the phenomenological waveform.
    \label{fig:heron:example:nonspin}
  }
\end{figure*}

\begin{figure*}
  \includegraphics[width=\textwidth]{figures/heron/antispin-equalmass.pdf}
  \caption[A Heron waveform from an aligned-spin system]
{\textbf{Anti-aligned spin waveform}. One hundred draws from the Gaussian process (left panel) for a non-spinning, equal-mass configuration ($\vec{s_1} = (0,0,0.6)$, $\vec{s_2} = (0,0,-0.6)$, $q = 1.0$), shown as light grey lines compared to two analytical approximant models, \texttt{SEOBNRv3} and \texttt{IMRPhenomPv2} in red and blue respectively. The mean draw from the Gaussian process is shown as a grey dashed line, while the associated variance is plotted as a grey-filled region surrounding the mean. In the right panel the distribution of mismatches between the samples and both phenomenological waveforms are shown, with the vertical lines representing the mismatch between the \gls{gp} regression and the phenomenological waveform.
    \label{fig:heron:example:spin}
  }
\end{figure*}

\begin{figure*}
  \includegraphics[width=\textwidth]{figures/heron/precessing.pdf}
  \caption[A Heron waveform from a precessing system]
{\textbf{Precessing waveform}. One hundred draws from the Gaussian process (left panel) for a precessing system, with a mass ratio $q=0.25$, and a spin configuration ($\vec{s_1} = (0.35,0.1,0.2)$, $\vec{s_2} = (0, 0, 0.4)$), shown as light grey lines compared to a single analytical approximant model, \texttt{IMRPhenomPv2} in blue. The mean draw from the Gaussian process is shown as a grey dashed line, while the associated variance is plotted as a grey-filled region surrounding the mean. In the right panel the distribution of mismatches between the samples and both phenomenological waveforms are shown, with the vertical line representing the mismatch between the \gls{gp} regression and the phenomenological waveform.
    \label{fig:heron:example:precessing}
  }
\end{figure*}


* Summary
\label{sec:heron:summary}

We have entered the era of routine abbr:gw detection, and the ability to accurately and rapidly characterise signals from events such as coalescences will be critical to understanding the properties of these systems. 
This characterisation process relies on the availability of waveform templates which are either precomputed prior to the analysis being run, or can be generated on-the-fly. 
Highly accurate waveforms, generated by simulations, are able, and in principal can facilitate accurate inference on detected signals. 
However, the expense of producing them limits their coverage of the parameter space; as a result of this lack of coverage, and the considerable time requirements to produce new waveforms, any inference method which relied solely on techniques could not hope to satisfy the requirement to rapidly
characterise signals, and would not be practical in a scenario where multiple events are detected every month. 
Phenomenological models, which can be evaluated rapidly, are available, which attempt to interpolate
across a large volume of the parameter space, but the accuracy of the waveforms which they produce can be difficult to assess. 
This leads to the possibility of introducing biases into the inferred properties of the system which generated the signal.

In this chapter I have laid-out an approach to producing a waveform model which is capable of producing estimates of the uncertainty in the waveform in addition to estimates of the gravitational waveform in regions of parameter space which have not been explored by abbr:nr simulations.
The ability to include these uncertainties should allow the accuracy of gravitational wave parameter estimation to be improved, as it allows biases introduced by uncertain waveform production to be taken into account.

In contrast to previous attempts to produce a abbr:gp based model for waveforms, such as cite:2017PhRvD..96l3011D, this model is trained on data from the Georgia Tech waveform catalogue, described in section ref:sec:heron:nrdata.
Other approaches have also been taken to producing surrogate models (eg the NRSur family of models cite:2015PhRvL.115l1102B,2017PhRvD..95j4023B,2017PhRvD..96b4058B (discussed in section ref:sec:sources:cbc:surrogates), however these approaches do not have the attractive feature of producing an estimate of the waveform uncertainty.

In section ref:sec:heron:verification I presented a number of tests which were used on the model to ensure that its outputs are reliable.
The results of these tests indicate that the Heron model is capable of producing similar matches against numerical relativity waveforms 

I have presented a number of waveforms which have been produced by the Heron model in section ref:sec:heron:verification, and make comparisons between its output and two phenomenological models. 
These comparisons show a difference between the behaviour of the two models which is most pronounced during the inspiral section of the waveform. 
This difference also occurs between the phenomenological model and the waveform produced from abbr:gp regression. 
A number of phenomena are likely to have contributed to this discrepancy. 
One such difference in the systematic errors of the simulations used to produce the training data for the model compared to those used to calibrate the phenomenological models. 
Additionally, the relatively small number of waveforms used to calibrate the phenomenological models compared to the model are likely to introduce systematic errors in the waveforms produced by those models. In order to reduce the effect of systematic errors from a larger model could include waveforms from a number of different waveform catalogues, however the addition of more waveforms will increase the memory requirements to both train and evaluate the model. 
The waveform model tends towards producing conservative estimates of the waveform, this is clearly visible in the variance of the precessing waveform in figure ref:fig:heron:example:precessing. 
The use of additional waveforms is likely to improve the confidence of the model's prediction.

In order for a abbr:gp-based approach such as this to be practical for parameter estimation studies using data from LIGO or Virgo it would be necessary to have a means of producing waveforms which are capable of modelling a greater amount of the inspiral than the Heron model can currently provide. 
One potential approach to solving this problem is hybridising the output waveform from the model with waveforms produced from a post-Newtonian approximant, in a similar manner to that used by
cite:2018arXiv181207865V.

# In conclusion, we have demonstrated that is capable of being used as an
# interpolant for waveforms, trained directly off data from simulations.
# While this method cannot hope to produce waveforms with the same
# precision as itself, it does account for the uncertainty introduced
# through interpolation, a feature which is valuable for preventing the
# introduction of bias in a analysis.

# * Acknowledgements

# The authors wish to thank Christopher Moore, Sebastian Khan, and Vijay
# Varma for their insightful comments and suggestions on an earleir draft
# of the manuscript.

# DW is supported by the Science and Technology Facilities Council (STFC)
# grant ST/N504075/1. ISH is supported by STFC grant ST/L000946/1. JC
# acknowledges support from NSF awards PHYS-1505824 and PHYS-1505524SH.

# This document has been assigned LIGO document reference LIGO-P1800128.
